#ifndef SMB_DATA_H
#define SMB_DATA_H

#include "stdint.h"
#include "constants.h"

extern const uint8_t data[32768];
#define PRG_IMAGE_SIZE 32768

#define ROM_ADDR_ExFl 0xd1ea
#define ROM_ADDR_ExHC 0xde38
#define ROM_ADDR_ExNH 0xf67f
#define ROM_ADDR_ExPF 0xd5d0
#define ROM_ADDR_ExTA 0xdb44
#define ROM_ADDR_LInj 0xd9ff
#define ROM_ADDR_NoFD 0xcc28
#define ROM_ADDR_PdbM 0xc9cb
#define ROM_ADDR_Rest 0xf792
#define ROM_ADDR_SOfs 0xedc3
#define ROM_ADDR_StnE 0xd7a1
#define ROM_ADDR_AddHA 0xcdcb
#define ROM_ADDR_AddHS 0xcabb
#define ROM_ADDR_AddVA 0xcdff
#define ROM_ADDR_AdjSm 0xce28
#define ROM_ADDR_BBFly 0xba73
#define ROM_ADDR_BHalf 0xdd85
#define ROM_ADDR_BPGet 0xcf1e
#define ROM_ADDR_BigBP 0xbd62
#define ROM_ADDR_BigJp 0xce31
#define ROM_ADDR_BotSP 0xedaa
#define ROM_ADDR_CInvu 0xdfe6
#define ROM_ADDR_ChkJH 0xc9e1
#define ROM_ADDR_ChkLS 0xcf31
#define ROM_ADDR_ChkW2 0xc6b4
#define ROM_ADDR_CntPl 0xeef3
#define ROM_ADDR_DecHT 0xca0a
#define ROM_ADDR_DoBPl 0xd43b
#define ROM_ADDR_EColl 0xd88a
#define ROM_ADDR_EndRp 0xd530
#define ROM_ADDR_ErACM 0xde1c
#define ROM_ADDR_ExCPV 0xdc51
#define ROM_ADDR_ExCSM 0xde02
#define ROM_ADDR_ExDPl 0xd63c
#define ROM_ADDR_ExEBG 0xdfb8
#define ROM_ADDR_ExF17 0xc710
#define ROM_ADDR_ExHCF 0xd7c3
#define ROM_ADDR_ExIPM 0xdf81
#define ROM_ADDR_ExLPC 0xdb78
#define ROM_ADDR_ExPEC 0xd8f8
#define ROM_ADDR_ExPGH 0xef33
#define ROM_ADDR_ExPHC 0xd7ff
#define ROM_ADDR_ExPRp 0xd597
#define ROM_ADDR_ExRPl 0xd64e
#define ROM_ADDR_ExS1H 0xf45a
#define ROM_ADDR_ExS2H 0xf5c1
#define ROM_ADDR_ExSCH 0xdd9b
#define ROM_ADDR_ExSFN 0xda24
#define ROM_ADDR_ExSPC 0xdbb7
#define ROM_ADDR_ExSPl 0xedde
#define ROM_ADDR_ExXMP 0xd630
#define ROM_ADDR_ExYPl 0xd606
#define ROM_ADDR_FPGfx 0xb8ac
#define ROM_ADDR_FallE 0xca98
#define ROM_ADDR_FireA 0xed02
#define ROM_ADDR_FlmEx 0xc59c
#define ROM_ADDR_FlyCC 0xceed
#define ROM_ADDR_Fr12S 0xcf40
#define ROM_ADDR_GSeed 0xc4e4
#define ROM_ADDR_HBChk 0xdfdf
#define ROM_ADDR_HJump 0xca4b
#define ROM_ADDR_Inc2B 0xc25e
#define ROM_ADDR_Inc3B 0xc25b
#define ROM_ADDR_InvtD 0xe0bd
#define ROM_ADDR_JSFnd 0xdee6
#define ROM_ADDR_JmpEO 0xc88f
#define ROM_ADDR_KSPts 0xd8f5
#define ROM_ADDR_LLeft 0x892a
#define ROM_ADDR_LRAir 0xb3ac
#define ROM_ADDR_LcChk 0xeb74
#define ROM_ADDR_LdLDa 0xcf47
#define ROM_ADDR_LongN 0xf868
#define ROM_ADDR_MEHor 0xcaaf
#define ROM_ADDR_MaxCC 0xc4c4
#define ROM_ADDR_MediN 0xf864
#define ROM_ADDR_MtchF 0xde70
#define ROM_ADDR_N2Prt 0xf3ec
#define ROM_ADDR_NSFnd 0xe1c7
#define ROM_ADDR_NXSpd 0xdf66
#define ROM_ADDR_NYSpd 0xdcf2
#define ROM_ADDR_NoOfs 0xe309
#define ROM_ADDR_NoPUp 0xd84c
#define ROM_ADDR_NoSSw 0xcc1b
#define ROM_ADDR_PlatF 0xdf74
#define ROM_ADDR_RImpd 0xdf5e
#define ROM_ADDR_RSeed 0xc4f8
#define ROM_ADDR_RXSpd 0xdb36
#define ROM_ADDR_RetXC 0xe429
#define ROM_ADDR_RetYC 0xe42b
#define ROM_ADDR_Row3C 0xeb7e
#define ROM_ADDR_RunFB 0xb6be
#define ROM_ADDR_RunFR 0xde73
#define ROM_ADDR_SBBAt 0xe8cd
#define ROM_ADDR_SBnce 0xd9f1
#define ROM_ADDR_SChk2 0xe61a
#define ROM_ADDR_SChk3 0xe624
#define ROM_ADDR_SChk4 0xe62e
#define ROM_ADDR_SChk5 0xe638
#define ROM_ADDR_SChk6 0xe642
#define ROM_ADDR_SChkA 0xe07b
#define ROM_ADDR_SFcRt 0xda0d
#define ROM_ADDR_SFlmX 0xd1f9
#define ROM_ADDR_SLChk 0xe64b
#define ROM_ADDR_SOLft 0xe31f
#define ROM_ADDR_SORte 0xe306
#define ROM_ADDR_SOfs2 0xedd1
#define ROM_ADDR_SUpdR 0xef76
#define ROM_ADDR_SetHJ 0xca37
#define ROM_ADDR_SetM2 0xd005
#define ROM_ADDR_SetMF 0xc614
#define ROM_ADDR_SetYO 0xc81f
#define ROM_ADDR_SideC 0xdc11
#define ROM_ADDR_SlowM 0xcab2
#define ROM_ADDR_SmSpc 0xf49d
#define ROM_ADDR_SndOn 0xf2d9
#define ROM_ADDR_Start 0x8000
#define ROM_ADDR_StkLp 0xe4b0
#define ROM_ADDR_StrID 0xc208
#define ROM_ADDR_SwimX 0xcbbb
#define ROM_ADDR_SzOfs 0xf09b
#define ROM_ADDR_TInjE 0xd923
#define ROM_ADDR_TopEx 0xbe40
#define ROM_ADDR_TopSP 0xed9c
#define ROM_ADDR_YSway 0xcb3b
#define ROM_ADDR_YesEC 0xda9b
#define ROM_ADDR_YesIn 0xdff2
#define ROM_ADDR_AddCCF 0xcf0c
#define ROM_ADDR_AlignP 0xc7ed
#define ROM_ADDR_AllMus 0xf8ef
#define ROM_ADDR_Alter2 0x96e2
#define ROM_ADDR_AxeObj 0x9a09
#define ROM_ADDR_BSwimE 0xcc03
#define ROM_ADDR_BWithL 0x9b28
#define ROM_ADDR_BigKTS 0xef2d
#define ROM_ADDR_CCSwim 0xcc53
#define ROM_ADDR_CMBits 0xe267
#define ROM_ADDR_CasPBB 0xc83b
#define ROM_ADDR_ChkInj 0xd8ff
#define ROM_ADDR_ChkLak 0xc3b4
#define ROM_ADDR_ChkRep 0xec0a
#define ROM_ADDR_ChkTop 0xbeaa
#define ROM_ADDR_ChkUpM 0xc018
#define ROM_ADDR_ChkWtr 0xb4d2
#define ROM_ADDR_Chk_BB 0xba1a
#define ROM_ADDR_ClHCol 0xd7fa
#define ROM_ADDR_CntGrp 0xc74d
#define ROM_ADDR_CoinSd 0xdfab
#define ROM_ADDR_ColFlg 0xd494
#define ROM_ADDR_ColObj 0x9a20
#define ROM_ADDR_ContES 0xeab6
#define ROM_ADDR_Demote 0xe02b
#define ROM_ADDR_DoSide 0xe182
#define ROM_ADDR_ECLoop 0xda56
#define ROM_ADDR_ESRtnr 0xeaca
#define ROM_ADDR_EggExc 0xeaf2
#define ROM_ADDR_ExBCDr 0xecdd
#define ROM_ADDR_ExCJSp 0xdedc
#define ROM_ADDR_ExDBlk 0xec52
#define ROM_ADDR_ExDBub 0xee06
#define ROM_ADDR_ExDLPl 0xe654
#define ROM_ADDR_ExEPar 0xc22d
#define ROM_ADDR_ExPVne 0xdebc
#define ROM_ADDR_ExSfx1 0xf4b5
#define ROM_ADDR_ExSfx2 0xf57b
#define ROM_ADDR_ExSfx3 0xf666
#define ROM_ADDR_ExSwCC 0xccc6
#define ROM_ADDR_ExitNA 0xb328
#define ROM_ADDR_ExitRp 0xd53e
#define ROM_ADDR_ExitVH 0xb9b7
#define ROM_ADDR_ExitWh 0xb7f4
#define ROM_ADDR_FBLeft 0xcba2
#define ROM_ADDR_FBallB 0xe23d
#define ROM_ADDR_FPS2nd 0xf3f2
#define ROM_ADDR_FSLoop 0xc577
#define ROM_ADDR_FlmeAt 0xd235
#define ROM_ADDR_Fthrow 0xf403
#define ROM_ADDR_GBBAdr 0xdcab
#define ROM_ADDR_GSltLp 0xc752
#define ROM_ADDR_GetHRp 0xd56a
#define ROM_ADDR_GetLRp 0xd550
#define ROM_ADDR_GetRow 0x9a44
#define ROM_ADDR_GrLoop 0xc750
#define ROM_ADDR_IncPXM 0xcb5d
#define ROM_ADDR_InitJS 0xb4a0
#define ROM_ADDR_JCoinC 0xbb6c
#define ROM_ADDR_JSMove 0xb3b3
#define ROM_ADDR_KillBB 0xba85
#define ROM_ADDR_LeftWh 0xb828
#define ROM_ADDR_LenSet 0x9bba
#define ROM_ADDR_LimitB 0xd68d
#define ROM_ADDR_LrgObj 0x95f8
#define ROM_ADDR_M1FOfs 0xd28b
#define ROM_ADDR_M2FOfs 0xd281
#define ROM_ADDR_M3FOfs 0xd277
#define ROM_ADDR_N2Tone 0xf538
#define ROM_ADDR_NKGmba 0xcaf8
#define ROM_ADDR_NVFLak 0xeb3e
#define ROM_ADDR_NextED 0xc784
#define ROM_ADDR_NextVO 0xb93d
#define ROM_ADDR_NextWh 0xb7f1
#define ROM_ADDR_NoBump 0xe131
#define ROM_ADDR_NoFore 0x9467
#define ROM_ADDR_NoJump 0xb488
#define ROM_ADDR_NoLAFr 0xe98d
#define ROM_ADDR_NoMGPT 0xcb44
#define ROM_ADDR_NoOfs2 0xe322
#define ROM_ADDR_NoTone 0xf39e
#define ROM_ADDR_NoZSup 0xbc46
#define ROM_ADDR_NotEgg 0xe977
#define ROM_ADDR_NotTRO 0xf757
#define ROM_ADDR_NotUse 0xc24d
#define ROM_ADDR_PTRegC 0xf327
#define ROM_ADDR_PUpOfs 0xe73b
#define ROM_ADDR_PlatDn 0xd4a4
#define ROM_ADDR_PlatSt 0xd49e
#define ROM_ADDR_PlatUp 0xd498
#define ROM_ADDR_PullID 0xc72f
#define ROM_ADDR_Row23C 0xeb89
#define ROM_ADDR_SBMDir 0xcbaa
#define ROM_ADDR_SBlasJ 0xf550
#define ROM_ADDR_SPBBox 0xc82b
#define ROM_ADDR_SaveAB 0xaf67
#define ROM_ADDR_SetBPA 0xc7f8
#define ROM_ADDR_SetFWC 0xd309
#define ROM_ADDR_SetFrT 0xc5c9
#define ROM_ADDR_SetPWh 0xb839
#define ROM_ADDR_SetYGp 0xc73a
#define ROM_ADDR_Shimmy 0xca62
#define ROM_ADDR_ShrPlF 0xf0e5
#define ROM_ADDR_SkipIY 0xd5ec
#define ROM_ADDR_SkipPT 0xc979
#define ROM_ADDR_SmTick 0xf49f
#define ROM_ADDR_SnglID 0xc730
#define ROM_ADDR_SpnySC 0xead3
#define ROM_ADDR_SteadM 0xcab4
#define ROM_ADDR_StrFre 0xc224
#define ROM_ADDR_SubtR1 0xcde2
#define ROM_ADDR_SwimKT 0xef1f
#define ROM_ADDR_ThirdP 0x9416
#define ROM_ADDR_TooFar 0xd6d2
#define ROM_ADDR_UpdSte 0xbed1
#define ROM_ADDR_VineTL 0xe479
#define ROM_ADDR_WhLoop 0xb7c7
#define ROM_ADDR_WhPull 0xb83b
#define ROM_ADDR_YMDown 0xd5fb
#define ROM_ADDR_YPDiff 0xccbf
#define ROM_ADDR_Y_Bubl 0xb748
#define ROM_ADDR_AddFBit 0xc6e6
#define ROM_ADDR_AllRowC 0xeb93
#define ROM_ADDR_AlterYP 0xbfe9
#define ROM_ADDR_BBChk_E 0xe3a5
#define ROM_ADDR_B_FaceP 0xd0b0
#define ROM_ADDR_BlstSJp 0xf5d1
#define ROM_ADDR_CNwCDir 0xe0c5
#define ROM_ADDR_CSzNext 0xf0c3
#define ROM_ADDR_ChgSDir 0xce6f
#define ROM_ADDR_Chk1stB 0x959d
#define ROM_ADDR_Chk2Ofs 0xce5c
#define ROM_ADDR_ChkDSte 0xba6a
#define ROM_ADDR_ChkFBCl 0xce58
#define ROM_ADDR_ChkFOfs 0xcde6
#define ROM_ADDR_ChkFTop 0xe492
#define ROM_ADDR_ChkNoEn 0xc3ca
#define ROM_ADDR_ChkPBtm 0xddbb
#define ROM_ADDR_ChkRBit 0xc6d6
#define ROM_ADDR_ChkSkid 0xb59e
#define ROM_ADDR_ChkStop 0xb2e3
#define ROM_ADDR_ChkVFBD 0xce3c
#define ROM_ADDR_ChnkOfs 0xecc9
#define ROM_ADDR_ClimbFD 0xb406
#define ROM_ADDR_ContChk 0xdd2d
#define ROM_ADDR_ContPau 0xf316
#define ROM_ADDR_CreateL 0xc3d3
#define ROM_ADDR_D2XPos1 0xc51c
#define ROM_ADDR_D2XPos2 0xc530
#define ROM_ADDR_DChunks 0xec65
#define ROM_ADDR_DSFLoop 0xd36d
#define ROM_ADDR_DecPauC 0xf32e
#define ROM_ADDR_DecSeXM 0xcb60
#define ROM_ADDR_DifLoop 0xc40f
#define ROM_ADDR_DisJoyp 0xb0ff
#define ROM_ADDR_DoGroup 0xc22e
#define ROM_ADDR_DrawRow 0x9a48
#define ROM_ADDR_ELPGive 0xd33f
#define ROM_ADDR_EndUChk 0x94ca
#define ROM_ADDR_EraseFB 0xb6ee
#define ROM_ADDR_EraseR1 0xd4f7
#define ROM_ADDR_EraseR2 0xd528
#define ROM_ADDR_ExAnimC 0xf08f
#define ROM_ADDR_ExBGfxH 0xd1bb
#define ROM_ADDR_ExCInvT 0xdec3
#define ROM_ADDR_ExDivPD 0xf281
#define ROM_ADDR_ExESdeC 0xe123
#define ROM_ADDR_ExFlmeD 0xd294
#define ROM_ADDR_ExJCGfx 0xe6bd
#define ROM_ADDR_ExLiftP 0xd679
#define ROM_ADDR_ExPipeE 0xdf4a
#define ROM_ADDR_ExPlPos 0xdc40
#define ROM_ADDR_ExTrans 0x92a9
#define ROM_ADDR_ExVMove 0xc046
#define ROM_ADDR_ExXMove 0xbf4c
#define ROM_ADDR_ExitEng 0xaf92
#define ROM_ADDR_ExitFWk 0xc689
#define ROM_ADDR_ExitPUp 0xbcea
#define ROM_ADDR_ExitPhy 0xb58b
#define ROM_ADDR_FBCLoop 0xce32
#define ROM_ADDR_FastXSp 0xb554
#define ROM_ADDR_FeetTmr 0xd094
#define ROM_ADDR_FinCCSt 0xc53c
#define ROM_ADDR_GMLoopB 0xf6d1
#define ROM_ADDR_Get17ID 0xc6bc
#define ROM_ADDR_GetCent 0xc355
#define ROM_ADDR_GetDToO 0xd0ea
#define ROM_ADDR_GetESpd 0xc316
#define ROM_ADDR_GetRBit 0xc6d1
#define ROM_ADDR_GetRow2 0x9a5f
#define ROM_ADDR_GetWNum 0xdf22
#define ROM_ADDR_GetXPhy 0xb55e
#define ROM_ADDR_GetYPhy 0xb4e4
#define ROM_ADDR_GndMove 0xb363
#define ROM_ADDR_GorSLog 0xf0c6
#define ROM_ADDR_HeadChk 0xdcba
#define ROM_ADDR_HoleDie 0xb194
#define ROM_ADDR_InPause 0xf2ee
#define ROM_ADDR_InitMLp 0xc122
#define ROM_ADDR_InvOBit 0xbd7b
#define ROM_ADDR_LRWater 0xb3a6
#define ROM_ADDR_NextVSp 0xe4a2
#define ROM_ADDR_NoBFall 0xd05e
#define ROM_ADDR_NoCDirF 0xe060
#define ROM_ADDR_NoColFB 0xce85
#define ROM_ADDR_NoFBall 0xb6f2
#define ROM_ADDR_NoFPObj 0xb2bf
#define ROM_ADDR_NoHFlip 0xf296
#define ROM_ADDR_NoIncPT 0xcb18
#define ROM_ADDR_NoIncXM 0xcb5c
#define ROM_ADDR_NoInter 0x86e0
#define ROM_ADDR_NoJSChk 0xbf59
#define ROM_ADDR_NoJSFnd 0xdee7
#define ROM_ADDR_NoKillE 0x9724
#define ROM_ADDR_NoPDwnL 0xf4d1
#define ROM_ADDR_NoPECol 0xd880
#define ROM_ADDR_NoReset 0x88ad
#define ROM_ADDR_NoSideC 0xdc14
#define ROM_ADDR_NoStop1 0xf6cf
#define ROM_ADDR_NoTTick 0xd327
#define ROM_ADDR_NoTopSc 0x8fbb
#define ROM_ADDR_NoUnder 0x97b0
#define ROM_ADDR_NormObj 0x9616
#define ROM_ADDR_NotDefB 0xcc3f
#define ROM_ADDR_NotTall 0x9847
#define ROM_ADDR_OffVine 0xb0c7
#define ROM_ADDR_PBFRegs 0xf5de
#define ROM_ADDR_PPHSubt 0xd626
#define ROM_ADDR_PTone1F 0xf312
#define ROM_ADDR_PTone2F 0xf325
#define ROM_ADDR_PosBubl 0xb714
#define ROM_ADDR_PosJSpr 0xb8d9
#define ROM_ADDR_RelWOfs 0xf142
#define ROM_ADDR_RenderH 0xe4f7
#define ROM_ADDR_ResJmpM 0xe3a3
#define ROM_ADDR_RetEOfs 0xc3e3
#define ROM_ADDR_RunAObj 0x965f
#define ROM_ADDR_RunAllH 0xbb28
#define ROM_ADDR_RunDemo 0x82c0
#define ROM_ADDR_Set17ID 0xc6c3
#define ROM_ADDR_SetBBox 0xc35c
#define ROM_ADDR_SetESpd 0xc319
#define ROM_ADDR_SetEntr 0xb1dd
#define ROM_ADDR_SetFore 0x96ee
#define ROM_ADDR_SetGfxF 0xd220
#define ROM_ADDR_SetHFAt 0xf2a0
#define ROM_ADDR_SetHPos 0xbb09
#define ROM_ADDR_SetHSpd 0xbaf3
#define ROM_ADDR_SetLMov 0xcf67
#define ROM_ADDR_SetLSpd 0xcf53
#define ROM_ADDR_SetMOfs 0xbaa0
#define ROM_ADDR_SetNotW 0xe04a
#define ROM_ADDR_SetPSte 0xdc84
#define ROM_ADDR_SetPVar 0xd628
#define ROM_ADDR_SetRSpd 0xcadf
#define ROM_ADDR_SetRTmr 0xb559
#define ROM_ADDR_SetSDir 0xce78
#define ROM_ADDR_SetShim 0xca75
#define ROM_ADDR_SetStun 0xe02f
#define ROM_ADDR_SetVFbr 0xce03
#define ROM_ADDR_SetVXPl 0xdea1
#define ROM_ADDR_SetoffF 0xd359
#define ROM_ADDR_SetupBB 0xba4d
#define ROM_ADDR_ShroomM 0xbcaa
#define ROM_ADDR_SizeChk 0xb12b
#define ROM_ADDR_SkipPIn 0xf344
#define ROM_ADDR_SkpFSte 0xcd65
#define ROM_ADDR_SkpVTop 0xe490
#define ROM_ADDR_SmallBP 0xbd61
#define ROM_ADDR_SpecObj 0x960d
#define ROM_ADDR_StoreMT 0x9488
#define ROM_ADDR_StrAObj 0x9656
#define ROM_ADDR_StrType 0xbc79
#define ROM_ADDR_StrWave 0xf37d
#define ROM_ADDR_SusFbar 0xcd55
#define ROM_ADDR_Unbreak 0xbd78
#define ROM_ADDR_UsePosv 0xc433
#define ROM_ADDR_VAHandl 0xcdee
#define ROM_ADDR_VBlank1 0x800a
#define ROM_ADDR_VBlank2 0x800f
#define ROM_ADDR_WarpNum 0x9701
#define ROM_ADDR_XMRight 0xcb7c
#define ROM_ADDR_AllUnder 0x97aa
#define ROM_ADDR_BB_SLoop 0xc6ff
#define ROM_ADDR_BackColC 0x9646
#define ROM_ADDR_Bitmasks 0xc68a
#define ROM_ADDR_BounceJS 0xb8f4
#define ROM_ADDR_BublExit 0xb686
#define ROM_ADDR_BublLoop 0xb675
#define ROM_ADDR_CSetFDir 0xb40a
#define ROM_ADDR_CarryOne 0x8f8e
#define ROM_ADDR_ChainObj 0x9a0e
#define ROM_ADDR_ChkBBill 0xe054
#define ROM_ADDR_ChkBrick 0xbd1a
#define ROM_ADDR_ChkETmrs 0xd90e
#define ROM_ADDR_ChkFiery 0x85fd
#define ROM_ADDR_ChkFireB 0xd149
#define ROM_ADDR_ChkGERtn 0xddf0
#define ROM_ADDR_ChkHoleX 0xb1aa
#define ROM_ADDR_ChkLuigi 0x8873
#define ROM_ADDR_ChkMTLow 0x94e0
#define ROM_ADDR_ChkMouth 0xd08c
#define ROM_ADDR_ChkOnScr 0xdc86
#define ROM_ADDR_ChkOverR 0x9197
#define ROM_ADDR_ChkPUSte 0xbcd2
#define ROM_ADDR_ChkRFast 0xb545
#define ROM_ADDR_ChkRow13 0x95c3
#define ROM_ADDR_ChkRow14 0x95b3
#define ROM_ADDR_ChkSRows 0x95e2
#define ROM_ADDR_ChkStPos 0x9153
#define ROM_ADDR_ChkStart 0x819d
#define ROM_ADDR_ChkSwimE 0x91b0
#define ROM_ADDR_ChpChpEx 0xc44e
#define ROM_ADDR_ClrMTBuf 0x9408
#define ROM_ADDR_ColdBoot 0x802b
#define ROM_ADDR_CompDToO 0xd107
#define ROM_ADDR_ContBTmr 0xbd39
#define ROM_ADDR_ContSChk 0xdda9
#define ROM_ADDR_CopyFToR 0xd187
#define ROM_ADDR_CycleTwo 0xaf5d
#define ROM_ADDR_DBlkLoop 0xebe7
#define ROM_ADDR_DecJpFPS 0xf419
#define ROM_ADDR_DemoOver 0x838a
#define ROM_ADDR_DivLLoop 0xf5ec
#define ROM_ADDR_DmpJpFPS 0xf3f4
#define ROM_ADDR_DoAction 0x8380
#define ROM_ADDR_DoLpBack 0xc11c
#define ROM_ADDR_DontWalk 0x83d0
#define ROM_ADDR_DownJSpr 0xb8d5
#define ROM_ADDR_DrawFbar 0xcd9c
#define ROM_ADDR_DrawJSpr 0xb902
#define ROM_ADDR_DrawPipe 0x9925
#define ROM_ADDR_DrawQBlk 0x9b2c
#define ROM_ADDR_DrawRope 0x99e9
#define ROM_ADDR_DrawVine 0xe435
#define ROM_ADDR_DumpFall 0xb38d
#define ROM_ADDR_EL_LRegs 0xf5e0
#define ROM_ADDR_EndMushL 0x978b
#define ROM_ADDR_EndTreeL 0x9773
#define ROM_ADDR_ExCannon 0xba30
#define ROM_ADDR_ExEBGChk 0xe066
#define ROM_ADDR_ExGTimer 0xb7a3
#define ROM_ADDR_ExLSHand 0xc3e5
#define ROM_ADDR_ExPBGCol 0xdc97
#define ROM_ADDR_ExPlyrAt 0xf129
#define ROM_ADDR_ExScrnBd 0xd6d5
#define ROM_ADDR_ExSteChk 0xe0a4
#define ROM_ADDR_ExXOfsBS 0xf22a
#define ROM_ADDR_ExYOfsBS 0xf26c
#define ROM_ADDR_ExitBoth 0xb268
#define ROM_ADDR_ExitBubl 0xb74a
#define ROM_ADDR_ExitCSub 0xb41f
#define ROM_ADDR_ExitCtrl 0xb1ba
#define ROM_ADDR_ExitEntr 0xb0e5
#define ROM_ADDR_ExitGetM 0x9115
#define ROM_ADDR_ExitIcon 0x833f
#define ROM_ADDR_ExitMenu 0x830d
#define ROM_ADDR_ExitMov1 0xb3c4
#define ROM_ADDR_ExitMsgs 0x8460
#define ROM_ADDR_ExitPipe 0x98ab
#define ROM_ADDR_ExtendLB 0xd68f
#define ROM_ADDR_FindLoop 0xc0d8
#define ROM_ADDR_GameIsOn 0x9281
#define ROM_ADDR_GameMode 0xaedc
#define ROM_ADDR_GameText 0x8752
#define ROM_ADDR_GetHPose 0xe4f0
#define ROM_ADDR_GetPRCmp 0xd0d1
#define ROM_ADDR_GetXPhy2 0xb56c
#define ROM_ADDR_GmbaAnim 0xe910
#define ROM_ADDR_InCastle 0xb2f1
#define ROM_ADDR_IncMLoop 0xc102
#define ROM_ADDR_InitByte 0x90dc
#define ROM_ADDR_InitLCmd 0xc12a
#define ROM_ADDR_InitRear 0x9636
#define ROM_ADDR_InitSteP 0xdd5a
#define ROM_ADDR_InitVStf 0xc363
#define ROM_ADDR_JCoinRun 0xbbc9
#define ROM_ADDR_KillLoop 0xd073
#define ROM_ADDR_KillVine 0xb98a
#define ROM_ADDR_LandPlyr 0xdd44
#define ROM_ADDR_LeavePar 0x9635
#define ROM_ADDR_LeftSwim 0xcbce
#define ROM_ADDR_LongBeat 0xf8b1
#define ROM_ADDR_LoopCmdE 0x9645
#define ROM_ADDR_Mask2MSB 0x95dd
#define ROM_ADDR_MidTreeL 0x9767
#define ROM_ADDR_MiscLoop 0xbb98
#define ROM_ADDR_MovPTDwn 0xcb22
#define ROM_ADDR_MoveAOId 0x9612
#define ROM_ADDR_MoveBubl 0xb732
#define ROM_ADDR_MoveEOfs 0xdb15
#define ROM_ADDR_MoveSubs 0xb34e
#define ROM_ADDR_NameLoop 0x8878
#define ROM_ADDR_Next3Slt 0xba2d
#define ROM_ADDR_NextAObj 0x956e
#define ROM_ADDR_NextArea 0xb315
#define ROM_ADDR_NextBUpd 0xbefe
#define ROM_ADDR_NextFbar 0xcdb2
#define ROM_ADDR_NextSdeC 0xe11c
#define ROM_ADDR_NextTBit 0x94b6
#define ROM_ADDR_NoAltPal 0x864f
#define ROM_ADDR_NoBlankP 0x989e
#define ROM_ADDR_NoChgMus 0xaf52
#define ROM_ADDR_NoCloud2 0x94a8
#define ROM_ADDR_NoHammer 0xbabf
#define ROM_ADDR_NoIncDAC 0xf377
#define ROM_ADDR_NoTimeUp 0x86a2
#define ROM_ADDR_NoWhirlP 0x9b73
#define ROM_ADDR_NotDOrD4 0xf854
#define ROM_ADDR_NotRsNum 0xe65c
#define ROM_ADDR_NotWPipe 0x9608
#define ROM_ADDR_PIntLoop 0xefa6
#define ROM_ADDR_PJumpSnd 0xb511
#define ROM_ADDR_PipeDwnS 0xddce
#define ROM_ADDR_PlayBeat 0xf8bb
#define ROM_ADDR_PlayBump 0xf3ff
#define ROM_ADDR_PlyrPipe 0xddd7
#define ROM_ADDR_PortLoop 0x8e6c
#define ROM_ADDR_PrintMsg 0x843c
#define ROM_ADDR_ProcMove 0xb33b
#define ROM_ADDR_ProcPRun 0xb52d
#define ROM_ADDR_ProcSkid 0xb5b3
#define ROM_ADDR_ProcSwim 0xb393
#define ROM_ADDR_PullOfsB 0xec45
#define ROM_ADDR_PutLives 0x884d
#define ROM_ADDR_PutOldMT 0xbd40
#define ROM_ADDR_PwrUpJmp 0xbc60
#define ROM_ADDR_RdyNextA 0xb2f6
#define ROM_ADDR_RendBBuf 0x94d3
#define ROM_ADDR_RendBack 0x941f
#define ROM_ADDR_RendFore 0x9455
#define ROM_ADDR_RendTerr 0x946d
#define ROM_ADDR_ResetMDr 0xd0a6
#define ROM_ADDR_RunHSubs 0xbb2b
#define ROM_ADDR_RunVSubs 0xb96a
#define ROM_ADDR_SJumpSnd 0xb51a
#define ROM_ADDR_SaveJoyp 0xb104
#define ROM_ADDR_SaveXSpd 0xbf23
#define ROM_ADDR_SceLoop1 0x9445
#define ROM_ADDR_SceLoop2 0x945f
#define ROM_ADDR_SdeCLoop 0xe10a
#define ROM_ADDR_SetAnimC 0xf08c
#define ROM_ADDR_SetBBox2 0xc7db
#define ROM_ADDR_SetBFlip 0xec21
#define ROM_ADDR_SetCATmr 0xddea
#define ROM_ADDR_SetCAnim 0xb475
#define ROM_ADDR_SetD6Ste 0xe0fc
#define ROM_ADDR_SetDBSte 0xd77d
#define ROM_ADDR_SetFBTmr 0xd173
#define ROM_ADDR_SetFallS 0xdc82
#define ROM_ADDR_SetHiMax 0xbf94
#define ROM_ADDR_SetKRout 0xd946
#define ROM_ADDR_SetLMovD 0xcf9c
#define ROM_ADDR_SetMFbar 0xcd96
#define ROM_ADDR_SetMdMax 0xbf8e
#define ROM_ADDR_SetOscrO 0xf280
#define ROM_ADDR_SetPESub 0x91b8
#define ROM_ADDR_SetPRout 0xd948
#define ROM_ADDR_SetPause 0x81c2
#define ROM_ADDR_SetSpSpd 0xc434
#define ROM_ADDR_SetStPos 0x9165
#define ROM_ADDR_SetWYSpd 0xe048
#define ROM_ADDR_SetupGFB 0xcd6a
#define ROM_ADDR_SkipByte 0x90de
#define ROM_ADDR_SkipFBar 0xcdba
#define ROM_ADDR_SkipFqL1 0xf798
#define ROM_ADDR_SkipMove 0xc902
#define ROM_ADDR_SkipToFB 0xd139
#define ROM_ADDR_SlowSwim 0xcc04
#define ROM_ADDR_SpawnFBr 0xd154
#define ROM_ADDR_SpinyRte 0xc440
#define ROM_ADDR_StarFChk 0xc64c
#define ROM_ADDR_StrBlock 0x94f5
#define ROM_ADDR_TallBBox 0xc35a
#define ROM_ADDR_TaskLoop 0x86e9
#define ROM_ADDR_TerMTile 0x947e
#define ROM_ADDR_TerrBChk 0x94aa
#define ROM_ADDR_TerrLoop 0x9491
#define ROM_ADDR_TimeUpOn 0xb79a
#define ROM_ADDR_UseAdder 0xbf2c
#define ROM_ADDR_UseMiscS 0xbb92
#define ROM_ADDR_VineEntr 0xb0ac
#define ROM_ADDR_WarpPipe 0x98f0
#define ROM_ADDR_WaterMus 0xf8ed
#define ROM_ADDR_WrCMTile 0xb999
#define ROM_ADDR_WrongChk 0xc115
#define ROM_ADDR_XLdBData 0xf21e
#define ROM_ADDR_XOfsLoop 0xf1fa
#define ROM_ADDR_XSpdSign 0xb617
#define ROM_ADDR_YLdBData 0xf260
#define ROM_ADDR_YOfsLoop 0xf23d
#define ROM_ADDR_AutoClimb 0xb1d1
#define ROM_ADDR_BlkOffscr 0xec35
#define ROM_ADDR_BlockCode 0xbdbd
#define ROM_ADDR_BorrowOne 0x8f87
#define ROM_ADDR_BumpBlock 0xbd9b
#define ROM_ADDR_CRendLoop 0x981b
#define ROM_ADDR_C_S_IGAtt 0xf117
#define ROM_ADDR_CheckRear 0x955d
#define ROM_ADDR_Chk1Row13 0x9530
#define ROM_ADDR_Chk1Row14 0x9554
#define ROM_ADDR_Chk2MSBSt 0xe0ec
#define ROM_ADDR_ChkCFloor 0x982d
#define ROM_ADDR_ChkEmySpd 0xcfcb
#define ROM_ADDR_ChkHiByte 0x8723
#define ROM_ADDR_ChkLakDif 0xcf7d
#define ROM_ADDR_ChkLeftCo 0xec46
#define ROM_ADDR_ChkLength 0x9571
#define ROM_ADDR_ChkPSpeed 0xcf9f
#define ROM_ADDR_ChkSelect 0x8258
#define ROM_ADDR_ChkSpinyO 0xcfc1
#define ROM_ADDR_CloudExit 0xb1bb
#define ROM_ADDR_ClrPlrPal 0xaf64
#define ROM_ADDR_CoinBlock 0xbb38
#define ROM_ADDR_ContVMove 0xbf6d
#define ROM_ADDR_CopyScore 0x8faf
#define ROM_ADDR_DBlockSte 0xbcfa
#define ROM_ADDR_DecTimers 0x8100
#define ROM_ADDR_DoAPTasks 0x92ba
#define ROM_ADDR_DoAltLoad 0xf817
#define ROM_ADDR_DrawBlock 0xebd1
#define ROM_ADDR_EndAParse 0x9588
#define ROM_ADDR_EndFrenzy 0xc7b8
#define ROM_ADDR_EnemyJump 0xe163
#define ROM_ADDR_EntrMode2 0xb09b
#define ROM_ADDR_ExJSpring 0xb91d
#define ROM_ADDR_ExMoveLak 0xcfdc
#define ROM_ADDR_ExitBlink 0xb253
#define ROM_ADDR_ExitDeath 0xb2a3
#define ROM_ADDR_ExitDrawM 0x8967
#define ROM_ADDR_ExitFlagP 0xb8b5
#define ROM_ADDR_ExitPause 0x81c5
#define ROM_ADDR_ExitVWalk 0x83f1
#define ROM_ADDR_FMiscLoop 0xbb86
#define ROM_ADDR_Floatdown 0xcc21
#define ROM_ADDR_GetHAdder 0xce9a
#define ROM_ADDR_GetLength 0x8eb3
#define ROM_ADDR_GetVAdder 0xceba
#define ROM_ADDR_GiveFPScr 0xb899
#define ROM_ADDR_GoombaDie 0xd706
#define ROM_ADDR_HammerChk 0xd10f
#define ROM_ADDR_ISpr0Loop 0x90b6
#define ROM_ADDR_IntroEntr 0xb08d
#define ROM_ADDR_IntroPipe 0x9882
#define ROM_ADDR_JoypFrict 0xb5db
#define ROM_ADDR_KeepOnscr 0xb013
#define ROM_ADDR_KillBlock 0xbecf
#define ROM_ADDR_KillELoop 0x971c
#define ROM_ADDR_KilledAtt 0xf105
#define ROM_ADDR_LakituChk 0xc7ba
#define ROM_ADDR_LeftFrict 0xb5de
#define ROM_ADDR_LuigiName 0x87ed
#define ROM_ADDR_MakeBJump 0xd13c
#define ROM_ADDR_MaskHPNyb 0x9204
#define ROM_ADDR_MatchBump 0xbe01
#define ROM_ADDR_MushLExit 0x97ce
#define ROM_ADDR_NPROffscr 0xef95
#define ROM_ADDR_NextFSlot 0xc7c6
#define ROM_ADDR_NextMTRow 0x892e
#define ROM_ADDR_NextStair 0x9ac1
#define ROM_ADDR_NoBGColor 0x85ee
#define ROM_ADDR_NoColWrap 0x92eb
#define ROM_ADDR_NoDecEnv1 0xf7b1
#define ROM_ADDR_NoDecEnv2 0xf80a
#define ROM_ADDR_NoFToECol 0xd72c
#define ROM_ADDR_NoHOffscr 0xe540
#define ROM_ADDR_NoMoveSub 0xb359
#define ROM_ADDR_NoRunCode 0xc8d6
#define ROM_ADDR_NoStopSfx 0xf6b1
#define ROM_ADDR_NotECstlM 0xf8e3
#define ROM_ADDR_NotGoomba 0xd710
#define ROM_ADDR_OtherRope 0xd4ff
#define ROM_ADDR_OutputCol 0x86f9
#define ROM_ADDR_PROfsLoop 0xef8c
#define ROM_ADDR_PauseSkip 0x811b
#define ROM_ADDR_PlayBlast 0xf53a
#define ROM_ADDR_PlayerRdy 0xb0d3
#define ROM_ADDR_ProcClimb 0xb465
#define ROM_ADDR_ProcELoop 0xaf03
#define ROM_ADDR_ProcLoopb 0x957b
#define ROM_ADDR_PutBehind 0xbc7b
#define ROM_ADDR_PutMTileB 0xbd41
#define ROM_ADDR_PutinPipe 0xd40a
#define ROM_ADDR_RdyDecode 0x9565
#define ROM_ADDR_RemBridge 0x8acd
#define ROM_ADDR_RenderPul 0x97c8
#define ROM_ADDR_ResGTCtrl 0xb786
#define ROM_ADDR_RghtFrict 0xb5fc
#define ROM_ADDR_RightPipe 0xb22e
#define ROM_ADDR_RunBBSubs 0xba76
#define ROM_ADDR_RunBowser 0xd065
#define ROM_ADDR_RunJCSubs 0xbbe8
#define ROM_ADDR_RunPUSubs 0xbcd8
#define ROM_ADDR_RunParser 0xaf8f
#define ROM_ADDR_SPixelLak 0xcfd6
#define ROM_ADDR_Save8Bits 0x8e8d
#define ROM_ADDR_ScreenOff 0x809e
#define ROM_ADDR_SetATHigh 0x897d
#define ROM_ADDR_SetAbsSpd 0xb620
#define ROM_ADDR_SetAttrib 0x8930
#define ROM_ADDR_SetBehind 0x956b
#define ROM_ADDR_SetCrouch 0xb338
#define ROM_ADDR_SetDplSpd 0xbfc5
#define ROM_ADDR_SetFor1Up 0xd83a
#define ROM_ADDR_SetForStn 0xe09a
#define ROM_ADDR_SetHmrTmr 0xd127
#define ROM_ADDR_SetRunSpd 0xb5ad
#define ROM_ADDR_SetupExpl 0xd2a5
#define ROM_ADDR_SetupNums 0x8f28
#define ROM_ADDR_SkipCtrlL 0xf7f1
#define ROM_ADDR_SkipScore 0xb896
#define ROM_ADDR_SmallBBox 0xc346
#define ROM_ADDR_StarBlock 0xbdd5
#define ROM_ADDR_StartBTmr 0xbd2c
#define ROM_ADDR_StartGame 0x8255
#define ROM_ADDR_StartPage 0x8ffe
#define ROM_ADDR_StoreFore 0x9c68
#define ROM_ADDR_StoreNewD 0x8f75
#define ROM_ADDR_SubDifAdj 0xcfd1
#define ROM_ADDR_TScrClear 0x8739
#define ROM_ADDR_TallBBox2 0xc7d9
#define ROM_ADDR_ThreeSChk 0xb9c3
#define ROM_ADDR_TransLoop 0x9297
#define ROM_ADDR_TreeLedge 0x974c
#define ROM_ADDR_UpToFiery 0xd847
#define ROM_ADDR_UpToSuper 0xd840
#define ROM_ADDR_VDrawLoop 0xb979
#define ROM_ADDR_VineBlock 0xbddf
#define ROM_ADDR_WaterPipe 0x986f
#define ROM_ADDR_X_Physics 0xb51c
#define ROM_ADDR_loc_33317 0x8225
#define ROM_ADDR_loc_39277 0x996d
#define ROM_ADDR_loc_39294 0x997e
#define ROM_ADDR_loc_39297 0x9981
#define ROM_ADDR_loc_48599 0xbdd7
#define ROM_ADDR_loc_48602 0xbdda
#define ROM_ADDR_loc_49081 0xbfb9
#define ROM_ADDR_loc_56355 0xdc23
#define ROM_ADDR_loc_58350 0xe3ee
#define ROM_ADDR_AddModLoop 0x8f68
#define ROM_ADDR_AddToScore 0xbc27
#define ROM_ADDR_AreaFrenzy 0x972b
#define ROM_ADDR_AttribLoop 0x8990
#define ROM_ADDR_AutoPlayer 0x839a
#define ROM_ADDR_Bridge_Low 0x997f
#define ROM_ADDR_ChkAreaTsk 0xc053
#define ROM_ADDR_ChkBehPipe 0xb083
#define ROM_ADDR_ChkBowserF 0xc05f
#define ROM_ADDR_ChkForFall 0xd44d
#define ROM_ADDR_ChkMoveDir 0xb13e
#define ROM_ADDR_ChkNearMid 0xafba
#define ROM_ADDR_ChkPOffscr 0xb000
#define ROM_ADDR_ChkRearSte 0xe955
#define ROM_ADDR_ClrGetLoop 0x860a
#define ROM_ADDR_ClrSndLoop 0x8fd6
#define ROM_ADDR_CoinPoints 0xbc22
#define ROM_ADDR_DemoEngine 0x836b
#define ROM_ADDR_DigitPLoop 0x8f47
#define ROM_ADDR_DoNothing1 0x92aa
#define ROM_ADDR_DoNothing2 0x92af
#define ROM_ADDR_DrawBowser 0xe949
#define ROM_ADDR_DrawBricks 0x9a38
#define ROM_ADDR_DrawBubble 0xede1
#define ROM_ADDR_DrawHammer 0xe4dc
#define ROM_ADDR_DrawMTLoop 0x88d0
#define ROM_ADDR_DumpSixSpr 0xe5b5
#define ROM_ADDR_DumpTwoSpr 0xe5c1
#define ROM_ADDR_EmptyBlock 0x9a19
#define ROM_ADDR_EndChgSize 0xb23d
#define ROM_ADDR_EndExitOne 0x8486
#define ROM_ADDR_EndExitTwo 0x849e
#define ROM_ADDR_EraseDMods 0x8f7c
#define ROM_ADDR_EraseMLoop 0x8f80
#define ROM_ADDR_ExitCAPipe 0xb21e
#define ROM_ADDR_ExitCastle 0x986e
#define ROM_ADDR_ExitELCore 0xc06a
#define ROM_ADDR_ExitUPartR 0x9bab
#define ROM_ADDR_FallingSub 0xb36d
#define ROM_ADDR_FireCannon 0xb9e9
#define ROM_ADDR_ForceHPose 0xe4ec
#define ROM_ADDR_GameEngine 0xaefe
#define ROM_ADDR_GetAreaPal 0x8a08
#define ROM_ADDR_GetHalfway 0x91f6
#define ROM_ADDR_GoContinue 0x830e
#define ROM_ADDR_HoleBottom 0xb1a6
#define ROM_ADDR_Hole_Empty 0x9b41
#define ROM_ADDR_Hole_Water 0x9957
#define ROM_ADDR_HurtBowser 0xd75c
#define ROM_ADDR_IncSubtask 0x8745
#define ROM_ADDR_InitATLoop 0x8e4d
#define ROM_ADDR_InitBowser 0xc549
#define ROM_ADDR_InitBuffer 0x80d0
#define ROM_ADDR_InitGoomba 0xc2f1
#define ROM_ADDR_InitLakitu 0xc385
#define ROM_ADDR_InitNTLoop 0x8e3b
#define ROM_ADDR_InitScores 0x8307
#define ROM_ADDR_InitScreen 0x858b
#define ROM_ADDR_InitScroll 0x8ee6
#define ROM_ADDR_JumpEngine 0x8e04
#define ROM_ADDR_Jumpspring 0x9ad3
#define ROM_ADDR_KillLakitu 0xc395
#define ROM_ADDR_KillPlayer 0xd958
#define ROM_ADDR_LdGameText 0x881b
#define ROM_ADDR_LoadHeader 0xf6f5
#define ROM_ADDR_MoveLakitu 0xcf28
#define ROM_ADDR_MoveOnVine 0xb3e0
#define ROM_ADDR_NoInitCode 0xc2f0
#define ROM_ADDR_NoMoveCode 0xc934
#define ROM_ADDR_NullJoypad 0x82bb
#define ROM_ADDR_OutputTScr 0x8719
#define ROM_ADDR_ParseRow0e 0xc231
#define ROM_ADDR_PlatLiftUp 0xc84b
#define ROM_ADDR_PlayerHole 0xb179
#define ROM_ADDR_PlayerStop 0x9869
#define ROM_ADDR_PlayerSubs 0xb14c
#define ROM_ADDR_ProcADLoop 0x950a
#define ROM_ADDR_RepeatByte 0x8eb9
#define ROM_ADDR_ResetTitle 0x82c9
#define ROM_ADDR_RightCheck 0x891a
#define ROM_ADDR_RowOfCoins 0x99f2
#define ROM_ADDR_SaveHAdder 0x8aa8
#define ROM_ADDR_SetAnimSpd 0xb5c5
#define ROM_ADDR_SetBGColor 0x8621
#define ROM_ADDR_SetHalfway 0x920f
#define ROM_ADDR_SetMoveDir 0xb14a
#define ROM_ADDR_SetSecHard 0x9047
#define ROM_ADDR_Setup_Vine 0xb91e
#define ROM_ADDR_SilenceHdr 0xf958
#define ROM_ADDR_SilentBeat 0xf8b9
#define ROM_ADDR_Sprite0Clr 0x813d
#define ROM_ADDR_Sprite0Hit 0x8150
#define ROM_ADDR_StoreMusic 0x9110
#define ROM_ADDR_StoreStyle 0x9ca3
#define ROM_ADDR_StrCOffset 0x9aa1
#define ROM_ADDR_StrWOffset 0x9b70
#define ROM_ADDR_StrongBeat 0xf8a9
#define ROM_ADDR_UpdateLoop 0xbed6
#define ROM_ADDR_UseBOffset 0x8a87
#define ROM_ADDR_WBootCheck 0x8018
#define ROM_ADDR_WaitOneRow 0x9ba0
#define ROM_ADDR_AreaPalette 0x85bb
#define ROM_ADDR_BlooberSwim 0xcbac
#define ROM_ADDR_Bridge_High 0x9979
#define ROM_ADDR_BubbleCheck 0xb6f9
#define ROM_ADDR_BumpChkLoop 0xbdf8
#define ROM_ADDR_C_ObjectRow 0x99fb
#define ROM_ADDR_ChgAreaMode 0xb213
#define ROM_ADDR_ChgAreaPipe 0xb20b
#define ROM_ADDR_Chk2Players 0x8815
#define ROM_ADDR_ChkAreaType 0x9106
#define ROM_ADDR_ChkCollSize 0xdc98
#define ROM_ADDR_ChkContinue 0x82d8
#define ROM_ADDR_ChkFrontSte 0xe940
#define ROM_ADDR_ChkNumTimer 0x84d1
#define ROM_ADDR_ChkSwimYPos 0xccac
#define ROM_ADDR_ChkWorldSel 0x826c
#define ROM_ADDR_ClearVRLoop 0x9077
#define ROM_ADDR_ClimbingSub 0xb3cf
#define ROM_ADDR_CreateSpiny 0xc3e6
#define ROM_ADDR_DeathMusHdr 0xf9b2
#define ROM_ADDR_DecNumTimer 0x84db
#define ROM_ADDR_DividePDiff 0xf26d
#define ROM_ADDR_DoFootCheck 0xdcf6
#define ROM_ADDR_DrawFirebar 0xeced
#define ROM_ADDR_DrawPowerUp 0xe6d2
#define ROM_ADDR_DrawThisRow 0x9b9d
#define ROM_ADDR_DumpFourSpr 0xe5bb
#define ROM_ADDR_EndGameText 0x882e
#define ROM_ADDR_EndlessLoop 0x8057
#define ROM_ADDR_EndlessRope 0x99d0
#define ROM_ADDR_ExEGHandler 0xeba9
#define ROM_ADDR_ExitAFrenzy 0x973c
#define ROM_ADDR_ExitChgSize 0xb244
#define ROM_ADDR_ExitChkName 0x8881
#define ROM_ADDR_ExitDumpSpr 0xe5c7
#define ROM_ADDR_ExitOutputN 0x8f5e
#define ROM_ADDR_FinishFlame 0xc61f
#define ROM_ADDR_FirebarSpin 0xd410
#define ROM_ADDR_FirebarYPos 0xcd3a
#define ROM_ADDR_FloateyPart 0x852b
#define ROM_ADDR_ForceInjury 0xd931
#define ROM_ADDR_FreCompLoop 0x9732
#define ROM_ADDR_GetAreaType 0x9c09
#define ROM_ADDR_GetBlankPal 0x89ef
#define ROM_ADDR_GetSteFromD 0xe0f9
#define ROM_ADDR_GiveOneCoin 0xbbfe
#define ROM_ADDR_HBlankDelay 0x8159
#define ROM_ADDR_IncWorldSel 0x829c
#define ROM_ADDR_InitBloober 0xc342
#define ROM_ADDR_InitCSTimer 0xb420
#define ROM_ADDR_InitPodoboo 0xc2f7
#define ROM_ADDR_InitScrlAmt 0xaffb
#define ROM_ADDR_InvEnemyDir 0xe140
#define ROM_ADDR_JumpSwimSub 0xb376
#define ROM_ADDR_KillEnemies 0x9716
#define ROM_ADDR_LargeLiftUp 0xc83f
#define ROM_ADDR_MoveBloober 0xcb89
#define ROM_ADDR_MovePodoboo 0xc9b0
#define ROM_ADDR_MoveVOffset 0x8a8f
#define ROM_ADDR_NextSubtask 0x85c8
#define ROM_ADDR_NoDecTimers 0x8119
#define ROM_ADDR_OutputInter 0x86c7
#define ROM_ADDR_PUpDrawLoop 0xe6f7
#define ROM_ADDR_PerformWalk 0x83cd
#define ROM_ADDR_PlayBigJump 0xf3d1
#define ROM_ADDR_PlaySqu1Sfx 0xf388
#define ROM_ADDR_PlaySqu2Sfx 0xf3a6
#define ROM_ADDR_PlayerDeath 0xb269
#define ROM_ADDR_PlayerInter 0x86c2
#define ROM_ADDR_PosPlatform 0xc871
#define ROM_ADDR_ProcFirebar 0xcd3c
#define ROM_ADDR_ProcJumping 0xb48b
#define ROM_ADDR_ReadJoypads 0x8e5c
#define ROM_ADDR_RowOfBricks 0x9a2e
#define ROM_ADDR_RunGameOver 0x9237
#define ROM_ADDR_SBwsrGfxOfs 0xe8fe
#define ROM_ADDR_SetBitsMask 0xda25
#define ROM_ADDR_SetEndTimer 0x8456
#define ROM_ADDR_SetFreq_Tri 0xf3ad
#define ROM_ADDR_SetVRAMCtrl 0x89bd
#define ROM_ADDR_SetXMoveAmt 0xbf96
#define ROM_ADDR_SetupBubble 0xb70b
#define ROM_ADDR_SetupCannon 0x9a85
#define ROM_ADDR_SetupLakitu 0xc38a
#define ROM_ADDR_SetupNumSpr 0x8537
#define ROM_ADDR_SetupWrites 0x8ea9
#define ROM_ADDR_ShufAmtLoop 0x90ab
#define ROM_ADDR_ShuffleLoop 0x81cf
#define ROM_ADDR_SilenceData 0xfa1c
#define ROM_ADDR_SkipSprite0 0x815c
#define ROM_ADDR_SlidePlayer 0xb2bc
#define ROM_ADDR_SoundEngine 0xf2d0
#define ROM_ADDR_SprInitLoop 0x8227
#define ROM_ADDR_Sprite0Data 0x8fcb
#define ROM_ADDR_StartClrGet 0x8606
#define ROM_ADDR_StartWorld1 0x82e6
#define ROM_ADDR_StillInGame 0x91e9
#define ROM_ADDR_ThankPlayer 0x8418
#define ROM_ADDR_VictoryMode 0x838b
#define ROM_ADDR_WarpNumLoop 0x8889
#define ROM_ADDR_WaterMusHdr 0xf96b
#define ROM_ADDR_World1Areas 0x9cbc
#define ROM_ADDR_World2Areas 0x9cc1
#define ROM_ADDR_World3Areas 0x9cc6
#define ROM_ADDR_World4Areas 0x9cca
#define ROM_ADDR_World5Areas 0x9ccf
#define ROM_ADDR_World6Areas 0x9cd3
#define ROM_ADDR_World7Areas 0x9cd7
#define ROM_ADDR_World8Areas 0x9cdc
#define ROM_ADDR_WriteNTAddr 0x8e2d
#define ROM_ADDR_BlankPalette 0x89c9
#define ROM_ADDR_BlockGfxData 0x8a39
#define ROM_ADDR_BrickShatter 0xbe02
#define ROM_ADDR_CastleMusHdr 0xf95c
#define ROM_ADDR_CastleObject 0x9806
#define ROM_ADDR_CheckHalfway 0x904a
#define ROM_ADDR_ChkFootMTile 0xdd1d
#define ROM_ADDR_ChkTallEnemy 0x8500
#define ROM_ADDR_ContinueGame 0x9264
#define ROM_ADDR_DeathMAltReg 0xf810
#define ROM_ADDR_DeathMusData 0xfb72
#define ROM_ADDR_DoChangeSize 0xef3a
#define ROM_ADDR_DoneInitArea 0x9054
#define ROM_ADDR_DrawFireball 0xecde
#define ROM_ADDR_DrawSidePart 0x98ce
#define ROM_ADDR_DrawStarFlag 0xd365
#define ROM_ADDR_DropPlatform 0xd631
#define ROM_ADDR_DumpThreeSpr 0xe5be
#define ROM_ADDR_E_WaterArea1 0xa160
#define ROM_ADDR_E_WaterArea2 0xa171
#define ROM_ADDR_E_WaterArea3 0xa19b
#define ROM_ADDR_EmptyChkLoop 0x994c
#define ROM_ADDR_EnemyLanding 0xe14f
#define ROM_ADDR_EnemyStomped 0xd969
#define ROM_ADDR_EvalForMusic 0x8434
#define ROM_ADDR_ExitBlockChk 0xbde7
#define ROM_ADDR_ExitColorRot 0x8a38
#define ROM_ADDR_ExitDecBlock 0x9b3c
#define ROM_ADDR_ExitEmptyChk 0x9956
#define ROM_ADDR_FirstSprXPos 0xe4c0
#define ROM_ADDR_FirstSprYPos 0xe4c4
#define ROM_ADDR_FrenzyIDData 0x9728
#define ROM_ADDR_FrictionData 0xb447
#define ROM_ADDR_GameOverMode 0x9218
#define ROM_ADDR_GameRoutines 0xb04a
#define ROM_ADDR_GameTextLoop 0x8820
#define ROM_ADDR_GetAltOffset 0x8523
#define ROM_ADDR_GetAreaMusic 0x90ed
#define ROM_ADDR_GetSBNybbles 0xbc30
#define ROM_ADDR_GetScoreDiff 0x8fa1
#define ROM_ADDR_GiveOEPoints 0xe016
#define ROM_ADDR_GoombaPoints 0xd7b6
#define ROM_ADDR_GrowItemRegs 0xf602
#define ROM_ADDR_IconDataRead 0x8327
#define ROM_ADDR_InitByteLoop 0x90d4
#define ROM_ADDR_InitPageLoop 0x90d2
#define ROM_ADDR_InitPlatScrl 0xb02e
#define ROM_ADDR_InitRedKoopa 0xc31e
#define ROM_ADDR_InjurePlayer 0xd92c
#define ROM_ADDR_KillFireBall 0xed61
#define ROM_ADDR_L_WaterArea1 0xae06
#define ROM_ADDR_L_WaterArea2 0xae45
#define ROM_ADDR_L_WaterArea3 0xaec0
#define ROM_ADDR_LoadNumTiles 0x84ed
#define ROM_ADDR_LoadSqu2Regs 0xf565
#define ROM_ADDR_MRetainerMsg 0x8414
#define ROM_ADDR_MiscLoopBack 0xbbf4
#define ROM_ADDR_MoveBoundBox 0xdba1
#define ROM_ADDR_MoveD_Bowser 0xd00f
#define ROM_ADDR_MusicHandler 0xf694
#define ROM_ADDR_NoFrenzyCode 0xc7b7
#define ROM_ADDR_OutputToVRAM 0x8eb6
#define ROM_ADDR_PRandomRange 0xd061
#define ROM_ADDR_Palette3Data 0x89d1
#define ROM_ADDR_PauseRoutine 0x8182
#define ROM_ADDR_PlatLiftDown 0xc857
#define ROM_ADDR_PlatformFall 0xd5bb
#define ROM_ADDR_PlayCoinGrab 0xf518
#define ROM_ADDR_PlayGrowVine 0xf600
#define ROM_ADDR_PlayNoiseSfx 0xf64d
#define ROM_ADDR_PlayerColors 0x85d7
#define ROM_ADDR_PlayerKilled 0xef40
#define ROM_ADDR_ProcJumpCoin 0xbba7
#define ROM_ADDR_ReadPortBits 0x8e6a
#define ROM_ADDR_RemoveBridge 0xd015
#define ROM_ADDR_ResetPalStar 0xb29a
#define ROM_ADDR_RunFireworks 0xd295
#define ROM_ADDR_RunGameTimer 0xb74f
#define ROM_ADDR_ScoreOffsets 0xbbfa
#define ROM_ADDR_ScrollScreen 0xafc4
#define ROM_ADDR_SelectBLogic 0x8276
#define ROM_ADDR_SetAmtOffset 0x81f2
#define ROM_ADDR_SetFreq_Squ1 0xf38b
#define ROM_ADDR_SetFreq_Squ2 0xf3a9
#define ROM_ADDR_SetupPowerUp 0xbc49
#define ROM_ADDR_ShrinkPlayer 0xf0d7
#define ROM_ADDR_SkipATRender 0x92c7
#define ROM_ADDR_SkipExpTimer 0x8116
#define ROM_ADDR_SkipMainOper 0x8178
#define ROM_ADDR_SolidOrClimb 0xdcea
#define ROM_ADDR_StarFlagExit 0xd311
#define ROM_ADDR_StrSprOffset 0x81e2
#define ROM_ADDR_UpdScrollVar 0xaf6f
#define ROM_ADDR_UpdateNumber 0xbc36
#define ROM_ADDR_UpdateScreen 0x8edd
#define ROM_ADDR_UpdateShroom 0x82a9
#define ROM_ADDR_VerticalPipe 0x98e5
#define ROM_ADDR_WaterMusData 0xfd52
#define ROM_ADDR_WriteBlankMT 0x8a58
#define ROM_ADDR_WritePPUReg1 0x8eed
#define ROM_ADDR_ActionFalling 0xf034
#define ROM_ADDR_ActionWalkRun 0xf03c
#define ROM_ADDR_AltYPosOffset 0x911a
#define ROM_ADDR_BowserControl 0xd07f
#define ROM_ADDR_BrickWithItem 0x9b19
#define ROM_ADDR_Bridge_Middle 0x997c
#define ROM_ADDR_CCSwimUpwards 0xcc99
#define ROM_ADDR_CastleMusData 0xfba4
#define ROM_ADDR_CheckForSpiny 0xe965
#define ROM_ADDR_ChkKillGoomba 0xcaeb
#define ROM_ADDR_ChkNearPlayer 0xcc29
#define ROM_ADDR_ChkPauseTimer 0x8194
#define ROM_ADDR_ChkUnderEnemy 0xe1ae
#define ROM_ADDR_ChkYCenterPos 0xd5ef
#define ROM_ADDR_ClearBitsMask 0xda2c
#define ROM_ADDR_ClimbAdderLow 0xb3c7
#define ROM_ADDR_ClrPauseTimer 0x81bd
#define ROM_ADDR_ClrTimersLoop 0x8fed
#define ROM_ADDR_ColorRotation 0x89e1
#define ROM_ADDR_ContinueBlast 0xf545
#define ROM_ADDR_ContinueMusic 0xf691
#define ROM_ADDR_DecTimersLoop 0x810e
#define ROM_ADDR_DisplayTimeUp 0x8693
#define ROM_ADDR_DoBulletBills 0xc6fd
#define ROM_ADDR_DrawEraseRope 0xd4bd
#define ROM_ADDR_DrawFlameLoop 0xd23c
#define ROM_ADDR_Dump_Sq2_Regs 0xf39f
#define ROM_ADDR_E_CastleArea1 0x9d70
#define ROM_ADDR_E_CastleArea2 0x9d97
#define ROM_ADDR_E_CastleArea3 0x9db0
#define ROM_ADDR_E_CastleArea4 0x9ddf
#define ROM_ADDR_E_CastleArea5 0x9e0a
#define ROM_ADDR_E_CastleArea6 0x9e1f
#define ROM_ADDR_E_GroundArea1 0x9e59
#define ROM_ADDR_E_GroundArea2 0x9e7e
#define ROM_ADDR_E_GroundArea3 0x9e9b
#define ROM_ADDR_E_GroundArea4 0x9ea9
#define ROM_ADDR_E_GroundArea5 0x9ed0
#define ROM_ADDR_E_GroundArea6 0x9f01
#define ROM_ADDR_E_GroundArea7 0x9f1f
#define ROM_ADDR_E_GroundArea8 0x9f3c
#define ROM_ADDR_E_GroundArea9 0x9f51
#define ROM_ADDR_EndAreaPoints 0xd336
#define ROM_ADDR_EndChkBButton 0x8487
#define ROM_ADDR_EnterSidePipe 0xb21f
#define ROM_ADDR_ExitECRoutine 0xdab1
#define ROM_ADDR_FlagpoleSlide 0xb2a4
#define ROM_ADDR_FlameYPosData 0xc59d
#define ROM_ADDR_GameOverInter 0x86d3
#define ROM_ADDR_GameTimerData 0x912d
#define ROM_ADDR_GetPipeHeight 0x9939
#define ROM_ADDR_HoleMetatiles 0x9b3d
#define ROM_ADDR_ImposeGravity 0xbfd7
#define ROM_ADDR_IncModeTask_A 0x845d
#define ROM_ADDR_IncModeTask_B 0x874e
#define ROM_ADDR_IncMsgCounter 0x8443
#define ROM_ADDR_InitFireworks 0xc63d
#define ROM_ADDR_InitHammerBro 0xc328
#define ROM_ADDR_L_CastleArea1 0xa1af
#define ROM_ADDR_L_CastleArea2 0xa210
#define ROM_ADDR_L_CastleArea3 0xa28f
#define ROM_ADDR_L_CastleArea4 0xa302
#define ROM_ADDR_L_CastleArea5 0xa36f
#define ROM_ADDR_L_CastleArea6 0xa3fa
#define ROM_ADDR_L_GroundArea1 0xa46b
#define ROM_ADDR_L_GroundArea2 0xa4ce
#define ROM_ADDR_L_GroundArea3 0xa537
#define ROM_ADDR_L_GroundArea4 0xa58a
#define ROM_ADDR_L_GroundArea5 0xa619
#define ROM_ADDR_L_GroundArea6 0xa68e
#define ROM_ADDR_L_GroundArea7 0xa6f3
#define ROM_ADDR_L_GroundArea8 0xa748
#define ROM_ADDR_L_GroundArea9 0xa7cd
#define ROM_ADDR_LakituDiffAdj 0xcf25
#define ROM_ADDR_LargeLiftBBox 0xc848
#define ROM_ADDR_LargeLiftDown 0xc845
#define ROM_ADDR_LoadAreaMusic 0xf6c8
#define ROM_ADDR_MushroomLedge 0x9778
#define ROM_ADDR_MusicLoopBack 0xf774
#define ROM_ADDR_NextSprOffset 0x81e5
#define ROM_ADDR_ObjOffsetData 0xf1a5
#define ROM_ADDR_OutputNumbers 0x8f11
#define ROM_ADDR_PlayExtraLife 0xf5e2
#define ROM_ADDR_PlaySmallJump 0xf3cd
#define ROM_ADDR_PlaySwimStomp 0xf45b
#define ROM_ADDR_PlayTimerTick 0xf51e
#define ROM_ADDR_ProcFireballs 0xb664
#define ROM_ADDR_ProcHammerBro 0xc9d8
#define ROM_ADDR_ProcHammerObj 0xbac3
#define ROM_ADDR_ProcSwimmingB 0xcbdf
#define ROM_ADDR_QuestionBlock 0x9b0e
#define ROM_ADDR_ReviveStunned 0xcac8
#define ROM_ADDR_RevivedXSpeed 0xc9d4
#define ROM_ADDR_RightPlatform 0xd63d
#define ROM_ADDR_RotPRandomBit 0x8131
#define ROM_ADDR_RunFirebarObj 0xc947
#define ROM_ADDR_ScrollHandler 0xaf93
#define ROM_ADDR_SecondPartMsg 0x8423
#define ROM_ADDR_SecondSprXPos 0xe4c8
#define ROM_ADDR_SecondSprYPos 0xe4cc
#define ROM_ADDR_SetFlameTimer 0xd1d9
#define ROM_ADDR_SetInitNTHigh 0x9012
#define ROM_ADDR_SetMiscOffset 0x81f9
#define ROM_ADDR_SetVRAMAddr_A 0x85c5
#define ROM_ADDR_SetVRAMAddr_B 0x864c
#define ROM_ADDR_SetVRAMOffset 0x863f
#define ROM_ADDR_SetupGameOver 0x9224
#define ROM_ADDR_SetupJumpCoin 0xbb51
#define ROM_ADDR_SideCheckLoop 0xdd66
#define ROM_ADDR_StarFlagExit2 0xd3af
#define ROM_ADDR_Star_CloudHdr 0xf943
#define ROM_ADDR_StatusBarData 0x8ef4
#define ROM_ADDR_StopGrowItems 0xf628
#define ROM_ADDR_StopPlatforms 0xd5b1
#define ROM_ADDR_SubtEnemyYPos 0xe15b
#define ROM_ADDR_SwimCC_IDData 0xc69a
#define ROM_ADDR_TerminateGame 0x9248
#define ROM_ADDR_TopScoreCheck 0x8f9e
#define ROM_ADDR_VPipeSectLoop 0x9890
#define ROM_ADDR_VictoryMusHdr 0xf961
#define ROM_ADDR_VineCollision 0xde7a
#define ROM_ADDR_VineYPosAdder 0xe433
#define ROM_ADDR_WriteGameText 0x8808
#define ROM_ADDR_WriteTopScore 0x8749
#define ROM_ADDR_ActionClimbing 0xf044
#define ROM_ADDR_ActionSwimming 0xf050
#define ROM_ADDR_AreaParserCore 0x93fc
#define ROM_ADDR_BlockBumpedChk 0xbdf6
#define ROM_ADDR_BrickMetatiles 0x9a29
#define ROM_ADDR_BrickWithCoins 0x9b14
#define ROM_ADDR_BridgeCollapse 0xcfec
#define ROM_ADDR_CannonBitmasks 0xb9ba
#define ROM_ADDR_CheckForGoomba 0xe900
#define ROM_ADDR_CheckForLakitu 0xe97a
#define ROM_ADDR_ChkBuzzyBeetle 0xd752
#define ROM_ADDR_ChkEnemyFrenzy 0xc12f
#define ROM_ADDR_ChkForFlagpole 0xde39
#define ROM_ADDR_ChkForRedKoopa 0xe0e2
#define ROM_ADDR_ChkYPCollision 0xd5fe
#define ROM_ADDR_ClimbAdderHigh 0xb3cb
#define ROM_ADDR_ClimbPLocAdder 0xde27
#define ROM_ADDR_ClimbXPosAdder 0xde25
#define ROM_ADDR_CollisionFound 0xe37e
#define ROM_ADDR_ColumnOfBricks 0x9a50
#define ROM_ADDR_CommonPlatCode 0xc828
#define ROM_ADDR_DecodeAreaData 0x9595
#define ROM_ADDR_DelayToAreaEnd 0xd3a2
#define ROM_ADDR_DemoActionData 0x8340
#define ROM_ADDR_DemoTimingData 0x8355
#define ROM_ADDR_DonePlayerTask 0xb273
#define ROM_ADDR_DrawPlayerLoop 0xefdc
#define ROM_ADDR_Dump_Freq_Regs 0xf38d
#define ROM_ADDR_Dump_Squ1_Regs 0xf381
#define ROM_ADDR_E_GroundArea10 0x9f7b
#define ROM_ADDR_E_GroundArea11 0x9f7c
#define ROM_ADDR_E_GroundArea12 0x9fa0
#define ROM_ADDR_E_GroundArea13 0x9fa9
#define ROM_ADDR_E_GroundArea14 0x9fce
#define ROM_ADDR_E_GroundArea15 0x9ff1
#define ROM_ADDR_E_GroundArea16 0x9ffa
#define ROM_ADDR_E_GroundArea17 0x9ffb
#define ROM_ADDR_E_GroundArea18 0xa035
#define ROM_ADDR_E_GroundArea19 0xa060
#define ROM_ADDR_E_GroundArea20 0xa08e
#define ROM_ADDR_E_GroundArea21 0xa0aa
#define ROM_ADDR_E_GroundArea22 0xa0b3
#define ROM_ADDR_EndOfMusicData 0xf74b
#define ROM_ADDR_ExitFBallEnemy 0xd733
#define ROM_ADDR_ExplosionTiles 0xed06
#define ROM_ADDR_FallMForceData 0xb42b
#define ROM_ADDR_FireBulletBill 0xc711
#define ROM_ADDR_FlagpoleObject 0x999e
#define ROM_ADDR_FlameTimerData 0xd1d1
#define ROM_ADDR_FlipBowserOver 0xe946
#define ROM_ADDR_FlyCCBPriority 0xceda
#define ROM_ADDR_FlyCCTimerData 0xc4a4
#define ROM_ADDR_GameOverMusHdr 0xf966
#define ROM_ADDR_GetAreaPalette 0x85bf
#define ROM_ADDR_GetMTileAttrib 0xdfb0
#define ROM_ADDR_GroundM_P1Data 0xfa01
#define ROM_ADDR_GrowThePowerUp 0xbcb3
#define ROM_ADDR_HammerXSpdData 0xba92
#define ROM_ADDR_HandleClimbing 0xde2e
#define ROM_ADDR_Hidden1UpBlock 0x9b01
#define ROM_ADDR_ImposeFriction 0xb5cc
#define ROM_ADDR_InitBulletBill 0xc36b
#define ROM_ADDR_InitChangeSize 0xb255
#define ROM_ADDR_InitCheepCheep 0xc375
#define ROM_ADDR_InitMForceData 0xb439
#define ROM_ADDR_InitRedPTroopa 0xc34a
#define ROM_ADDR_InitializeArea 0x8fe4
#define ROM_ADDR_InitializeGame 0x8fcf
#define ROM_ADDR_JumpMForceData 0xb424
#define ROM_ADDR_KillAllEnemies 0xd071
#define ROM_ADDR_L_GroundArea10 0xa832
#define ROM_ADDR_L_GroundArea11 0xa83b
#define ROM_ADDR_L_GroundArea12 0xa87a
#define ROM_ADDR_L_GroundArea13 0xa88f
#define ROM_ADDR_L_GroundArea14 0xa8f6
#define ROM_ADDR_L_GroundArea15 0xa95b
#define ROM_ADDR_L_GroundArea16 0xa9ce
#define ROM_ADDR_L_GroundArea17 0xa9ff
#define ROM_ADDR_L_GroundArea18 0xaa92
#define ROM_ADDR_L_GroundArea19 0xab05
#define ROM_ADDR_L_GroundArea20 0xab7e
#define ROM_ADDR_L_GroundArea21 0xabd7
#define ROM_ADDR_L_GroundArea22 0xac02
#define ROM_ADDR_LoadEventMusic 0xf6a4
#define ROM_ADDR_LoadTriCtrlReg 0xf86a
#define ROM_ADDR_MirrorEnemyGfx 0xead7
#define ROM_ADDR_MoveBulletBill 0xcc36
#define ROM_ADDR_MovePlatformUp 0xbfb7
#define ROM_ADDR_MoveRedPTroopa 0xbf77
#define ROM_ADDR_NormalXSpdData 0xc30c
#define ROM_ADDR_PlatPosDataLow 0xc86b
#define ROM_ADDR_PlayBowserFall 0xf5c8
#define ROM_ADDR_PlaySmackEnemy 0xf47d
#define ROM_ADDR_PlayerEndLevel 0xb2ca
#define ROM_ADDR_PlayerEndWorld 0x8461
#define ROM_ADDR_PlayerEntrance 0xb069
#define ROM_ADDR_PlayerLoseLife 0x91cd
#define ROM_ADDR_PlayerYSpdData 0xb432
#define ROM_ADDR_PrincessSaved1 0x8da8
#define ROM_ADDR_PrincessSaved2 0x8dbf
#define ROM_ADDR_ProcAirBubbles 0xb66e
#define ROM_ADDR_ProcessCannons 0xb9bc
#define ROM_ADDR_ReadyNextEnemy 0xdaaa
#define ROM_ADDR_RedPTroopaGrav 0xbfd1
#define ROM_ADDR_RemoveCoin_Axe 0x8a4d
#define ROM_ADDR_RunBowserFlame 0xc935
#define ROM_ADDR_RunRetainerObj 0xc8d7
#define ROM_ADDR_RunStarFlagObj 0xd2d9
#define ROM_ADDR_ScreenRoutines 0x8567
#define ROM_ADDR_ShrinkPlatform 0xe5e9
#define ROM_ADDR_SpawnFromMouth 0xc5ec
#define ROM_ADDR_SpawnHammerObj 0xba94
#define ROM_ADDR_SpriteShuffler 0x81c6
#define ROM_ADDR_StopPlayerMove 0xddff
#define ROM_ADDR_StopSquare1Sfx 0xf4a7
#define ROM_ADDR_StopSquare2Sfx 0xf571
#define ROM_ADDR_TriNoteHandler 0xf83e
#define ROM_ADDR_UnderHammerBro 0xe196
#define ROM_ADDR_UpdateTopScore 0x8f97
#define ROM_ADDR_VictoryMusData 0xfec8
#define ROM_ADDR_VineHeightData 0xb949
#define ROM_ADDR_Vine_AutoClimb 0xb1c7
#define ROM_ADDR_WarpZoneObject 0xb7a4
#define ROM_ADDR_AreaAddrOffsets 0x9cbc
#define ROM_ADDR_AreaDataAddrLow 0x9d2c
#define ROM_ADDR_AreaParserTasks 0x92c8
#define ROM_ADDR_AreaStyleObject 0x9740
#define ROM_ADDR_BackSceneryData 0x92fa
#define ROM_ADDR_BalancePlatRope 0x99d7
#define ROM_ADDR_BalancePlatform 0xd432
#define ROM_ADDR_BlockBufferAddr 0x9bdd
#define ROM_ADDR_BlooberBitmasks 0xcb87
#define ROM_ADDR_BoundingBoxCore 0xe29c
#define ROM_ADDR_BubbleTimerData 0xb74d
#define ROM_ADDR_CGrab_TTickRegL 0xf522
#define ROM_ADDR_CastleBridgeObj 0x9a01
#define ROM_ADDR_CastleMetatiles 0x97cf
#define ROM_ADDR_CheckBowserRear 0xe94c
#define ROM_ADDR_CheckForBloober 0xe9de
#define ROM_ADDR_CheckForJumping 0xb479
#define ROM_ADDR_CheckForPodoboo 0xe8e1
#define ROM_ADDR_CheckPlayerName 0x885f
#define ROM_ADDR_CheckSfx1Buffer 0xf43f
#define ROM_ADDR_CheckSfx2Buffer 0xf5a6
#define ROM_ADDR_CheckSideMTiles 0xdd9c
#define ROM_ADDR_CheckThreeBytes 0xc250
#define ROM_ADDR_CheckTopOfBlock 0xbe1f
#define ROM_ADDR_ChkForFloatdown 0xcc1c
#define ROM_ADDR_ChkForNonSolids 0xe1b5
#define ROM_ADDR_ChkLrgObjLength 0x9bac
#define ROM_ADDR_ChkOtherEnemies 0xd789
#define ROM_ADDR_ChkOtherForFall 0xd462
#define ROM_ADDR_ClearBounceFlag 0xe1ef
#define ROM_ADDR_CommonSmallLift 0xc860
#define ROM_ADDR_ContinueSndJump 0xf3df
#define ROM_ADDR_DoIDCheckBGColl 0xdfd8
#define ROM_ADDR_DoOtherPlatform 0xd4a7
#define ROM_ADDR_DrawBrickChunks 0xec53
#define ROM_ADDR_DrawEnemyObjRow 0xebaa
#define ROM_ADDR_DrawEnemyObject 0xea4b
#define ROM_ADDR_DrawTitleScreen 0x86ff
#define ROM_ADDR_EmptySfx2Buffer 0xf56d
#define ROM_ADDR_Enemy17YPosData 0xc692
#define ROM_ADDR_EnemyFacePlayer 0xda05
#define ROM_ADDR_EnemyGfxHandler 0xe87d
#define ROM_ADDR_EnemySmackScore 0xd7bc
#define ROM_ADDR_EnemyStompedPts 0xd996
#define ROM_ADDR_EnemyTurnAround 0xdb1c
#define ROM_ADDR_FindAreaPointer 0x9c13
#define ROM_ADDR_FireballObjCore 0xb689
#define ROM_ADDR_FirstBoxGreater 0xe35f
#define ROM_ADDR_FirstSprTilenum 0xe4d0
#define ROM_ADDR_FlagpoleRoutine 0xb855
#define ROM_ADDR_FlyCCXSpeedData 0xc498
#define ROM_ADDR_ForeSceneryData 0x93b1
#define ROM_ADDR_FourFrameExtent 0xf068
#define ROM_ADDR_GameCoreRoutine 0xaeea
#define ROM_ADDR_GameMenuRoutine 0x8245
#define ROM_ADDR_GameOverMusData 0xfc45
#define ROM_ADDR_GameTextOffsets 0x87fe
#define ROM_ADDR_GetAreaObjectID 0x9b36
#define ROM_ADDR_GetLrgObjAttrib 0x9bbb
#define ROM_ADDR_GetMiscBoundBox 0xe236
#define ROM_ADDR_GetPlayerColors 0x85f1
#define ROM_ADDR_GroundMLdInData 0xfaf9
#define ROM_ADDR_GroundM_P2AData 0xfa49
#define ROM_ADDR_GroundM_P2BData 0xfa75
#define ROM_ADDR_GroundM_P2CData 0xfa9d
#define ROM_ADDR_GroundM_P3AData 0xfac2
#define ROM_ADDR_GroundM_P3BData 0xfadb
#define ROM_ADDR_GroundM_P4AData 0xfb25
#define ROM_ADDR_GroundM_P4BData 0xfb4b
#define ROM_ADDR_GroundM_P4CData 0xfb74
#define ROM_ADDR_HammerBroBGColl 0xe185
#define ROM_ADDR_HammerSprAttrib 0xe4d8
#define ROM_ADDR_HandlePipeEntry 0xdee8
#define ROM_ADDR_HighPosUnitData 0xf237
#define ROM_ADDR_InitBalPlatform 0xc7df
#define ROM_ADDR_InitBowserFlame 0xc5a3
#define ROM_ADDR_InitEnemyFrenzy 0xc7a0
#define ROM_ADDR_InitEnemyObject 0xc226
#define ROM_ADDR_InitLongFirebar 0xc459
#define ROM_ADDR_InitNormalEnemy 0xc30e
#define ROM_ADDR_InitRetainerObj 0xc307
#define ROM_ADDR_JCoinGfxHandler 0xe686
#define ROM_ADDR_JumpRegContents 0xf3d3
#define ROM_ADDR_LoadAreaPointer 0x9c03
#define ROM_ADDR_LoadControlRegs 0xf8d8
#define ROM_ADDR_MaxLeftXSpdData 0xb440
#define ROM_ADDR_MaxSpdBlockData 0xbf9f
#define ROM_ADDR_MiscObjectsCore 0xbb96
#define ROM_ADDR_MoveNormalEnemy 0xca77
#define ROM_ADDR_MovePlayerYAxis 0xb200
#define ROM_ADDR_MoveWithXMCntrs 0xcb66
#define ROM_ADDR_MushFlowerBlock 0xbdd2
#define ROM_ADDR_MusicHeaderData 0xf90d
#define ROM_ADDR_MusicSelectData 0x90e7
#define ROM_ADDR_NoiseSfxHandler 0xf667
#define ROM_ADDR_NonAnimatedActs 0xf028
#define ROM_ADDR_OnePlayerTimeUp 0x87a0
#define ROM_ADDR_Palette0_MTiles 0x8b10
#define ROM_ADDR_Palette1_MTiles 0x8bac
#define ROM_ADDR_Palette2_MTiles 0x8c64
#define ROM_ADDR_Palette3_MTiles 0x8c8c
#define ROM_ADDR_PlatPosDataHigh 0xc86e
#define ROM_ADDR_PlayBowserFlame 0xf680
#define ROM_ADDR_PlayGrowPowerUp 0xf5fc
#define ROM_ADDR_PlayPipeDownInj 0xf4b6
#define ROM_ADDR_PlayPowerUpGrab 0xf552
#define ROM_ADDR_PlayerEnemyDiff 0xe143
#define ROM_ADDR_PowerUpGfxTable 0xe6be
#define ROM_ADDR_ProcBowserFlame 0xd1eb
#define ROM_ADDR_ProcLoopCommand 0xc0cc
#define ROM_ADDR_ProcessAreaData 0x9508
#define ROM_ADDR_PutPlayerOnVine 0xde88
#define ROM_ADDR_RenderPlayerSub 0xefbe
#define ROM_ADDR_RenderUnderPart 0x9b7d
#define ROM_ADDR_RevivalRateData 0xd9d2
#define ROM_ADDR_ScoreUpdateData 0x84b7
#define ROM_ADDR_ShellCollisions 0xdad9
#define ROM_ADDR_SidePipeTopPart 0x98a3
#define ROM_ADDR_SkipToOffScrChk 0xea61
#define ROM_ADDR_Squ1NoteHandler 0xf7dc
#define ROM_ADDR_Squ2NoteHandler 0xf786
#define ROM_ADDR_StaircaseObject 0x9ab7
#define ROM_ADDR_Star_CloudMData 0xf9b8
#define ROM_ADDR_StatusBarOffset 0x8f00
#define ROM_ADDR_SwimCCXMoveData 0xcc46
#define ROM_ADDR_SwimKickTileNum 0xeee7
#define ROM_ADDR_TitleScreenMode 0x8231
#define ROM_ADDR_TwoPlayerTimeUp 0x8798
#define ROM_ADDR_WarpZoneNumbers 0x87f2
#define ROM_ADDR_WarpZoneWelcome 0x87c0
#define ROM_ADDR_WinCastleMusHdr 0xf971
#define ROM_ADDR_WinLevelMusData 0xfcb0
#define ROM_ADDR_XMovingPlatform 0xd607
#define ROM_ADDR_XSpeedAdderData 0xc9d0
#define ROM_ADDR_YMovingPlatform 0xd5d3
#define ROM_ADDR_AnimationControl 0xf06f
#define ROM_ADDR_AreaDataAddrHigh 0x9d4e
#define ROM_ADDR_AreaDataHOffsets 0x9d28
#define ROM_ADDR_AreaMusicEnvData 0xff9a
#define ROM_ADDR_AwardTouchedCoin 0xdd1a
#define ROM_ADDR_BGColorCtrl_Addr 0x85cb
#define ROM_ADDR_BackgroundColors 0x85cf
#define ROM_ADDR_BlockObjectsCore 0xbe70
#define ROM_ADDR_BoundBoxCtrlData 0xe1fd
#define ROM_ADDR_BowserGfxHandler 0xd17b
#define ROM_ADDR_BowserIdentities 0xd736
#define ROM_ADDR_BulletBillCannon 0x9a69
#define ROM_ADDR_C_ObjectMetatile 0x99fe
#define ROM_ADDR_CheckBalPlatform 0xd440
#define ROM_ADDR_CheckBowserFront 0xe923
#define ROM_ADDR_CheckEndofBuffer 0xc150
#define ROM_ADDR_CheckNoiseBuffer 0xf675
#define ROM_ADDR_CheckPageCtrlRow 0xc189
#define ROM_ADDR_CheckRightBounds 0xc164
#define ROM_ADDR_ChkFlagOffscreen 0xe5a7
#define ROM_ADDR_ChkSmallPlatLoop 0xdb8c
#define ROM_ADDR_ChkToMoveBalPlat 0xd474
#define ROM_ADDR_ChkToStunEnemies 0xe01b
#define ROM_ADDR_CoinMetatileData 0x99ee
#define ROM_ADDR_CoinTallyOffsets 0xbbf8
#define ROM_ADDR_Cont_CGrab_TTick 0xf5c2
#define ROM_ADDR_DoEnemySideCheck 0xe0fe
#define ROM_ADDR_DrawFlagSetTimer 0xd396
#define ROM_ADDR_DrawMushroomIcon 0x8325
#define ROM_ADDR_DrawOneSpriteRow 0xebb2
#define ROM_ADDR_DrawSpriteObject 0xf282
#define ROM_ADDR_EndOfLevelMusHdr 0xf949
#define ROM_ADDR_EnemiesCollision 0xda33
#define ROM_ADDR_EnemyBGCXSpdData 0xdfbf
#define ROM_ADDR_EnemyDataAddrLow 0x9ce4
#define ROM_ADDR_EraseEnemyObject 0xc998
#define ROM_ADDR_ExInjColRoutines 0xd955
#define ROM_ADDR_ExecGameLoopback 0xc08c
#define ROM_ADDR_ExitMusicHandler 0xf8c4
#define ROM_ADDR_ExitProcessEColl 0xdaf0
#define ROM_ADDR_FindPlayerAction 0xef34
#define ROM_ADDR_FireballXSpdData 0xb687
#define ROM_ADDR_FirebarCollision 0xce08
#define ROM_ADDR_FlagpoleYPosData 0xde29
#define ROM_ADDR_FlipPUpRightSide 0xe72b
#define ROM_ADDR_FreqRegLookupTbl 0xff00
#define ROM_ADDR_GetAreaDataAddrs 0x9c22
#define ROM_ADDR_GetEnemyBoundBox 0xe243
#define ROM_ADDR_HandleChangeSize 0xf0b0
#define ROM_ADDR_HandleNoiseMusic 0xf86d
#define ROM_ADDR_ImpedePlayerMove 0xdf4b
#define ROM_ADDR_IncAreaObjOffset 0x9589
#define ROM_ADDR_IncrementSFTask1 0xd30e
#define ROM_ADDR_IncrementSFTask2 0xd39e
#define ROM_ADDR_InitBlock_XY_Pos 0xbd84
#define ROM_ADDR_InitDropPlatform 0xc803
#define ROM_ADDR_InitHoriPlatform 0xc80b
#define ROM_ADDR_InitJumpGPTroopa 0xc7d1
#define ROM_ADDR_InitPiranhaPlant 0xc787
#define ROM_ADDR_InitPlatformFall 0xd598
#define ROM_ADDR_InitShortFirebar 0xc45c
#define ROM_ADDR_InitVertPlatform 0xc812
#define ROM_ADDR_InitializeMemory 0x90cc
#define ROM_ADDR_JumpToDecLength2 0xf5c5
#define ROM_ADDR_JumpingCoinTiles 0xe682
#define ROM_ADDR_LoadEnvelopeData 0xf8f4
#define ROM_ADDR_LoadUsualEnvData 0xf8ff
#define ROM_ADDR_LoopCmdYPosition 0xc081
#define ROM_ADDR_MakePlatformFall 0xd45f
#define ROM_ADDR_MaxRightXSpdData 0xb443
#define ROM_ADDR_MoveColOffscreen 0xec4a
#define ROM_ADDR_MoveDropPlatform 0xbf88
#define ROM_ADDR_MoveJumpingEnemy 0xcaf9
#define ROM_ADDR_MovePiranhaPlant 0xd3b0
#define ROM_ADDR_MovePlatformDown 0xbfb4
#define ROM_ADDR_MoveRedPTroopaUp 0xbf75
#define ROM_ADDR_MushroomIconData 0x831d
#define ROM_ADDR_NMovShellFallBit 0xe0db
#define ROM_ADDR_NoCollisionFound 0xe37a
#define ROM_ADDR_NoEToBGCollision 0xdff7
#define ROM_ADDR_NoEnemyCollision 0xdaa1
#define ROM_ADDR_NoUnderHammerBro 0xe1a7
#define ROM_ADDR_NoiseBeatHandler 0xf88a
#define ROM_ADDR_OnGroundStateSub 0xb35a
#define ROM_ADDR_PRDiffAdjustData 0xc398
#define ROM_ADDR_PlayBrickShatter 0xf63b
#define ROM_ADDR_PlayerChangeSize 0xb233
#define ROM_ADDR_PlayerFireFlower 0xb27d
#define ROM_ADDR_PlayerGfxHandler 0xeee9
#define ROM_ADDR_PlayerLakituDiff 0xcf6c
#define ROM_ADDR_PlayerPhysicsSub 0xb450
#define ROM_ADDR_PositionEnemyObj 0xc1ab
#define ROM_ADDR_PrimaryGameSetup 0x9061
#define ROM_ADDR_ProcOnGroundActs 0xf00b
#define ROM_ADDR_ProcessEnemyData 0xc144
#define ROM_ADDR_PulleyRopeObject 0x97ba
#define ROM_ADDR_PutAtRightExtent 0xc5d8
#define ROM_ADDR_PutBlockMetatile 0x8a97
#define ROM_ADDR_ResetScreenTimer 0x88a5
#define ROM_ADDR_ResidualXSpdData 0xd84d
#define ROM_ADDR_RowOfSolidBlocks 0x9a3e
#define ROM_ADDR_RunLargePlatform 0xc965
#define ROM_ADDR_RunNormalEnemies 0xc8e0
#define ROM_ADDR_RunSmallPlatform 0xc94d
#define ROM_ADDR_ScrollLockObject 0x970d
#define ROM_ADDR_SecondSprTilenum 0xe4d4
#define ROM_ADDR_SetCollisionFlag 0xdbeb
#define ROM_ADDR_SetLast2Platform 0xe5eb
#define ROM_ADDR_SetupVictoryMode 0x83b0
#define ROM_ADDR_SixSpriteStacker 0xe4ae
#define ROM_ADDR_SpawnBrickChunks 0xbe41
#define ROM_ADDR_StaircaseRowData 0x9aae
#define ROM_ADDR_StarFlagTileData 0xd2d5
#define ROM_ADDR_StatusBarNybbles 0xbbfc
#define ROM_ADDR_TerrainMetatiles 0x93d8
#define ROM_ADDR_ThreeFrameExtent 0xf06d
#define ROM_ADDR_TopStatusBarLine 0x8752
#define ROM_ADDR_TransposePlayers 0x9282
#define ROM_ADDR_VerticalPipeData 0x98dd
#define ROM_ADDR_VictoryMLoopBack 0xf777
#define ROM_ADDR_WaterPaletteData 0x8ca4
#define ROM_ADDR_WorldAddrOffsets 0x9cb4
#define ROM_ADDR_X_SubtracterData 0xb034
#define ROM_ADDR_AutoControlPlayer 0xb0e6
#define ROM_ADDR_BSceneDataOffsets 0x92f7
#define ROM_ADDR_BowserPaletteData 0x8d4c
#define ROM_ADDR_Bubble_MForceData 0xb74b
#define ROM_ADDR_BulletBillHandler 0xba33
#define ROM_ADDR_BuzzyBeetleMutate 0xc1fd
#define ROM_ADDR_CastlePaletteData 0x8d10
#define ROM_ADDR_CheckForESymmetry 0xeaa6
#define ROM_ADDR_CheckForHammerBro 0xe9ca
#define ROM_ADDR_CheckFrenzyBuffer 0xc216
#define ROM_ADDR_CheckpointEnemyID 0xc26c
#define ROM_ADDR_ChkEnemyFaceRight 0xd9f6
#define ROM_ADDR_ChkForDemoteKoopa 0xd9b3
#define ROM_ADDR_ChkPlayerNearPipe 0xd3cf
#define ROM_ADDR_Climb_Y_SpeedData 0xb44a
#define ROM_ADDR_CollisionCoreLoop 0xe32d
#define ROM_ADDR_ContinueBumpThrow 0xf40d
#define ROM_ADDR_ContinueExtraLife 0xf5e7
#define ROM_ADDR_ContinueGrowItems 0xf60f
#define ROM_ADDR_ContinueSwimStomp 0xf469
#define ROM_ADDR_DefaultSprOffsets 0x8fbc
#define ROM_ADDR_DigitsMathRoutine 0x8f5f
#define ROM_ADDR_DoPlayerSideCheck 0xdd5e
#define ROM_ADDR_DrawLargePlatform 0xe5c8
#define ROM_ADDR_DrawSmallPlatform 0xed66
#define ROM_ADDR_DuplicateEnemyObj 0xc575
#define ROM_ADDR_EnemyAddrHOffsets 0x9ce0
#define ROM_ADDR_EnemyBGCStateData 0xdfb9
#define ROM_ADDR_EnemyDataAddrHigh 0x9d06
#define ROM_ADDR_EnemyMovementSubs 0xc905
#define ROM_ADDR_ExtraLifeFreqData 0xf4d4
#define ROM_ADDR_FSceneDataOffsets 0x93ae
#define ROM_ADDR_FindEmptyMiscSlot 0xbb84
#define ROM_ADDR_FireballExplosion 0xb6f3
#define ROM_ADDR_FirebarMirrorData 0xcd2a
#define ROM_ADDR_FirebarTblOffsets 0xcd2e
#define ROM_ADDR_FireworksXPosData 0xc631
#define ROM_ADDR_FireworksYPosData 0xc637
#define ROM_ADDR_FlagpoleCollision 0xde41
#define ROM_ADDR_FlagpoleScoreMods 0xb84b
#define ROM_ADDR_FlameYMFAdderData 0xc5a1
#define ROM_ADDR_GetGfxOffsetAdder 0xf091
#define ROM_ADDR_GetScreenPosition 0xb038
#define ROM_ADDR_GetXOffscreenBits 0xf1f6
#define ROM_ADDR_GetYOffscreenBits 0xf239
#define ROM_ADDR_GroundPaletteData 0x8cc8
#define ROM_ADDR_HammerBroJumpCode 0xca12
#define ROM_ADDR_HandleAxeMetatile 0xde0e
#define ROM_ADDR_Hidden1UpCoinAmts 0xb2c2
#define ROM_ADDR_InitEnemyRoutines 0xc27f
#define ROM_ADDR_JumpspringHandler 0xb8ba
#define ROM_ADDR_LandEnemyProperly 0xe067
#define ROM_ADDR_LoopCmdPageNumber 0xc076
#define ROM_ADDR_MoveDefeatedEnemy 0xcae5
#define ROM_ADDR_MoveEnemySlowVert 0xbf8c
#define ROM_ADDR_MoveHammerBroXDir 0xca58
#define ROM_ADDR_MoveLargeLiftPlat 0xd64f
#define ROM_ADDR_MoveLiftPlatforms 0xd65b
#define ROM_ADDR_MoveRedPTUpOrDown 0xcb19
#define ROM_ADDR_MoveSmallPlatform 0xd655
#define ROM_ADDR_OnePlayerGameOver 0x87b3
#define ROM_ADDR_PRandomSubtracter 0xced5
#define ROM_ADDR_PlayFireballThrow 0xf3f9
#define ROM_ADDR_PlayFlagpoleSlide 0xf3bf
#define ROM_ADDR_PlayerAnimTmrData 0xb58c
#define ROM_ADDR_PlayerBGCollision 0xdc64
#define ROM_ADDR_PlayerCtrlRoutine 0xb0e9
#define ROM_ADDR_PlayerInjuryBlink 0xb245
#define ROM_ADDR_PlayerVictoryWalk 0x83bd
#define ROM_ADDR_PowerUpAttributes 0xe6ce
#define ROM_ADDR_PowerUpObjHandler 0xbc85
#define ROM_ADDR_ProcessBowserHalf 0xd1bc
#define ROM_ADDR_ProcessLengthData 0xf8cb
#define ROM_ADDR_ProcessWhirlpools 0xb7b8
#define ROM_ADDR_ReversePlantSpeed 0xd3d5
#define ROM_ADDR_RunOffscrBitsSubs 0xf1d7
#define ROM_ADDR_SetupEOffsetFBBox 0xe27c
#define ROM_ADDR_SetupIntermediate 0x859b
#define ROM_ADDR_SetupPlatformRope 0xd541
#define ROM_ADDR_SetupToMovePPlant 0xd3e0
#define ROM_ADDR_Shroom_Flower_PUp 0xd820
#define ROM_ADDR_SideExitPipeEntry 0xb206
#define ROM_ADDR_SidePipeShaftData 0x989f
#define ROM_ADDR_Squ2LengthHandler 0xf77a
#define ROM_ADDR_Square1SfxHandler 0xf41b
#define ROM_ADDR_Square2SfxHandler 0xf57c
#define ROM_ADDR_StarFlagXPosAdder 0xd2d1
#define ROM_ADDR_StarFlagYPosAdder 0xd2cd
#define ROM_ADDR_TerrainRenderBits 0x93dc
#define ROM_ADDR_TimeRunOutMusData 0xfc72
#define ROM_ADDR_TimeRunningOutHdr 0xf93e
#define ROM_ADDR_TwoPlayerGameOver 0x87ab
#define ROM_ADDR_UndergroundMusHdr 0xf953
#define ROM_ADDR_VerticalPipeEntry 0xb1e5
#define ROM_ADDR_VineObjectHandler 0xb94b
#define ROM_ADDR_WhirlpoolActivate 0xb7f5
#define ROM_ADDR_WorldLivesDisplay 0x8779
#define ROM_ADDR_BlockBuffLowBounds 0x9504
#define ROM_ADDR_BlockObjMT_Updater 0xbed4
#define ROM_ADDR_BlockYPosAdderData 0xbceb
#define ROM_ADDR_BowserFlameEnvData 0xffca
#define ROM_ADDR_BranchToDecLength1 0xf47b
#define ROM_ADDR_BridgeCollapseData 0xcfdd
#define ROM_ADDR_BulletBillXSpdData 0xba31
#define ROM_ADDR_CheckAnimationStop 0xea29
#define ROM_ADDR_CheckBowserGfxFlag 0xe8f2
#define ROM_ADDR_CheckDefeatedState 0xea37
#define ROM_ADDR_CheckForCoinMTiles 0xdfa1
#define ROM_ADDR_CheckForDefdGoomba 0xe9ba
#define ROM_ADDR_CheckForEnemyGroup 0xc1f1
#define ROM_ADDR_CheckForJumpspring 0xe8d5
#define ROM_ADDR_ChkForPlayerAttrib 0xf0e9
#define ROM_ADDR_ChkForPlayerInjury 0xd8f9
#define ROM_ADDR_ChkForTopCollision 0xdbcf
#define ROM_ADDR_ChkInvisibleMTiles 0xdebd
#define ROM_ADDR_ClimbMTileUpperExt 0xdf96
#define ROM_ADDR_Climb_Y_MForceData 0xb44d
#define ROM_ADDR_ColorRotatePalette 0x89c3
#define ROM_ADDR_ContinueBowserFall 0xf5d3
#define ROM_ADDR_ContinueCGrabTTick 0xf52c
#define ROM_ADDR_ContinueSmackEnemy 0xf48d
#define ROM_ADDR_CyclePlayerPalette 0xb288
#define ROM_ADDR_DaySnowPaletteData 0x8d34
#define ROM_ADDR_E_UndergroundArea1 0xa0d8
#define ROM_ADDR_E_UndergroundArea2 0xa105
#define ROM_ADDR_E_UndergroundArea3 0xa133
#define ROM_ADDR_EndOfCastleMusData 0xfe51
#define ROM_ADDR_EndOfEnemyInitCode 0xc881
#define ROM_ADDR_EnemyAttributeData 0xe85b
#define ROM_ADDR_EnemyGraphicsTable 0xe73e
#define ROM_ADDR_ExtraLifeMushBlock 0xbdd8
#define ROM_ADDR_FetchNoiseBeatData 0xf878
#define ROM_ADDR_FetchSqu1MusicData 0xf7c5
#define ROM_ADDR_FindEmptyEnemySlot 0x994a
#define ROM_ADDR_FirebarSpinDirData 0xc454
#define ROM_ADDR_FirebarSpinSpdData 0xc44f
#define ROM_ADDR_FlagBalls_Residual 0x9994
#define ROM_ADDR_FlagpoleGfxHandler 0xe54b
#define ROM_ADDR_FloateyNumTileData 0x849f
#define ROM_ADDR_FlyCCXPositionData 0xc488
#define ROM_ADDR_GameTimerFireworks 0xd2f2
#define ROM_ADDR_GetBackgroundColor 0x85e3
#define ROM_ADDR_GetBlockBufferAddr 0x9be1
#define ROM_ADDR_GetFirebarPosition 0xce8e
#define ROM_ADDR_GetPlayerAnimSpeed 0xb58f
#define ROM_ADDR_GetProperObjOffset 0xf1a8
#define ROM_ADDR_HalfwayPageNybbles 0x91bd
#define ROM_ADDR_HammerBroJumpLData 0xca10
#define ROM_ADDR_HammerEnemyOfsData 0xba89
#define ROM_ADDR_HammerThrowTmrData 0xc9ce
#define ROM_ADDR_HandleCoinMetatile 0xde05
#define ROM_ADDR_HandleGroupEnemies 0xc71b
#define ROM_ADDR_HandlePECollisions 0xd895
#define ROM_ADDR_HandleSquare1Music 0xf7bc
#define ROM_ADDR_HandleSquare2Music 0xf73a
#define ROM_ADDR_ImposeGravityBlock 0xbfa4
#define ROM_ADDR_IncrementColumnPos 0x92db
#define ROM_ADDR_KickedShellPtsData 0xd892
#define ROM_ADDR_L_UndergroundArea1 0xac35
#define ROM_ADDR_L_UndergroundArea2 0xacd8
#define ROM_ADDR_L_UndergroundArea3 0xad79
#define ROM_ADDR_LandEnemyInitState 0xe0cd
#define ROM_ADDR_LoopCmdWorldNumber 0xc06b
#define ROM_ADDR_LuigiThanksMessage 0x8d68
#define ROM_ADDR_MarioThanksMessage 0x8d54
#define ROM_ADDR_MiscSqu1MusicTasks 0xf7f7
#define ROM_ADDR_MiscSqu2MusicTasks 0xf79e
#define ROM_ADDR_MoveRedPTroopaDown 0xbf70
#define ROM_ADDR_PUp_VGrow_FreqData 0xf4f8
#define ROM_ADDR_PlayerMovementSubs 0xb329
#define ROM_ADDR_PlayerOffscreenChk 0xef7a
#define ROM_ADDR_PlayerPosSPlatData 0xdc17
#define ROM_ADDR_ProcEnemyDirection 0xe0a5
#define ROM_ADDR_ProcMoveRedPTroopa 0xcaff
#define ROM_ADDR_RenderAreaGraphics 0x88ae
#define ROM_ADDR_RenderSidewaysPipe 0x98b3
#define ROM_ADDR_ResetPalFireFlower 0xb297
#define ROM_ADDR_ResidualHeaderData 0xf94e
#define ROM_ADDR_SecondaryGameSetup 0x9071
#define ROM_ADDR_SetPlatformTilenum 0xe5fd
#define ROM_ADDR_SetupFloateyNumber 0xda11
#define ROM_ADDR_ShellOrBlockDefeat 0xd795
#define ROM_ADDR_SidePipeBottomPart 0x98a7
#define ROM_ADDR_SolidMTileUpperExt 0xdf8b
#define ROM_ADDR_SprObjectOffscrChk 0xeb64
#define ROM_ADDR_UndergroundMusData 0xfd11
#define ROM_ADDR_VRAM_AddrTable_Low 0x805a
#define ROM_ADDR_VRAM_Buffer_Offset 0x8080
#define ROM_ADDR_WriteBlockMetatile 0x8a6d
#define ROM_ADDR_WriteTopStatusLine 0x8652
#define ROM_ADDR_XMoveCntr_Platform 0xcb47
#define ROM_ADDR_XOffscreenBitsData 0xf1e3
#define ROM_ADDR_YOffscreenBitsData 0xf22b
#define ROM_ADDR_AlterAreaAttributes 0x96c5
#define ROM_ADDR_AreaChangeTimerData 0xde03
#define ROM_ADDR_AreaDataOfsLoopback 0x9bf8
#define ROM_ADDR_BlockBuffer_X_Adder 0xe3b0
#define ROM_ADDR_BlockBuffer_Y_Adder 0xe3cc
#define ROM_ADDR_BrickShatterEnvData 0xffea
#define ROM_ADDR_CheckForClimbMTiles 0xdf9a
#define ROM_ADDR_CheckForRetainerObj 0xe8a9
#define ROM_ADDR_CheckForSecondFrame 0xea22
#define ROM_ADDR_CheckForSolidMTiles 0xdf8f
#define ROM_ADDR_CheckLeftScreenBBox 0xe30c
#define ROM_ADDR_CheckPlayerVertical 0xdc41
#define ROM_ADDR_CheckRightExtBounds 0xc1cb
#define ROM_ADDR_CheckToAnimateEnemy 0xe9fa
#define ROM_ADDR_CheckToMirrorLakitu 0xeb12
#define ROM_ADDR_ChkFlagpoleYPosLoop 0xde68
#define ROM_ADDR_ChkLandedEnemyState 0xe07e
#define ROM_ADDR_ColumnOfSolidBlocks 0x9a59
#define ROM_ADDR_ContinueBowserFlame 0xf685
#define ROM_ADDR_ContinuePipeDownInj 0xf4bb
#define ROM_ADDR_ContinuePowerUpGrab 0xf557
#define ROM_ADDR_DecrementSfx1Length 0xf4a2
#define ROM_ADDR_DecrementSfx2Length 0xf568
#define ROM_ADDR_DecrementSfx3Length 0xf658
#define ROM_ADDR_DefaultXOnscreenOfs 0xf1f3
#define ROM_ADDR_DefaultYOnscreenOfs 0xf234
#define ROM_ADDR_DisplayIntermediate 0x86a8
#define ROM_ADDR_EnemiesAndLoopsCore 0xc047
#define ROM_ADDR_FindAreaMusicHeader 0xf6ed
#define ROM_ADDR_FireballBGCollision 0xe1c8
#define ROM_ADDR_FireballEnemyCDLoop 0xd6ee
#define ROM_ADDR_FirebarPosLookupTbl 0xccc7
#define ROM_ADDR_FireworksSoundScore 0xd2bd
#define ROM_ADDR_FlagpoleScoreDigits 0xb850
#define ROM_ADDR_FlipEnemyVertically 0xea8a
#define ROM_ADDR_GetAreaObjXPosition 0x9bcb
#define ROM_ADDR_GetAreaObjYPosition 0x9bd3
#define ROM_ADDR_GetEnemyBoundBoxOfs 0xdc52
#define ROM_ADDR_GetFireballBoundBox 0xe22d
#define ROM_ADDR_GetMaskedOffScrBits 0xe252
#define ROM_ADDR_GetOffScreenBitsSet 0xf1c0
#define ROM_ADDR_GroundLevelPart1Hdr 0xf976
#define ROM_ADDR_HandleEnemyFBallCol 0xd73e
#define ROM_ADDR_HandleStompedShellE 0xd9d4
#define ROM_ADDR_HandleTriangleMusic 0xf81a
#define ROM_ADDR_ImposeGravitySprObj 0xbfad
#define ROM_ADDR_InitFireballExplode 0xe1f4
#define ROM_ADDR_KickedShellXSpdData 0xd84f
#define ROM_ADDR_KillEnemyAboveBlock 0xe18e
#define ROM_ADDR_MoveDefeatedBloober 0xcbdc
#define ROM_ADDR_MoveFallingPlatform 0xbf6b
#define ROM_ADDR_MoveFlyGreenPTroopa 0xcb25
#define ROM_ADDR_MushroomPaletteData 0x8d44
#define ROM_ADDR_PlayerBGUpperExtent 0xdc62
#define ROM_ADDR_PlayerCollisionCore 0xe325
#define ROM_ADDR_PlayerGfxProcessing 0xef45
#define ROM_ADDR_PlayerGfxTblOffsets 0xee07
#define ROM_ADDR_PlayerGraphicsTable 0xee17
#define ROM_ADDR_PlayerHeadCollision 0xbced
#define ROM_ADDR_PowerUpGrabFreqData 0xf4da
#define ROM_ADDR_ProcEnemyCollisions 0xdab4
#define ROM_ADDR_ProcFireball_Bubble 0xb624
#define ROM_ADDR_ProcLPlatCollisions 0xdbbc
#define ROM_ADDR_ProcSPlatCollisions 0xdbba
#define ROM_ADDR_ProcSecondEnemyColl 0xdaf1
#define ROM_ADDR_ProcessPlayerAction 0xefec
#define ROM_ADDR_PulleyRopeMetatiles 0x97b7
#define ROM_ADDR_ResidualGravityCode 0xbfa1
#define ROM_ADDR_RunEnemyObjectsCore 0xc882
#define ROM_ADDR_RunSoundSubroutines 0xf34b
#define ROM_ADDR_SetOffscrBitsOffset 0xf1ba
#define ROM_ADDR_SolidBlockMetatiles 0x9a25
#define ROM_ADDR_StaircaseHeightData 0x9aa5
#define ROM_ADDR_StompedEnemyPtsData 0xd965
#define ROM_ADDR_VRAM_AddrTable_High 0x806d
#define ROM_ADDR_WorldSelectMessage1 0x8dde
#define ROM_ADDR_WorldSelectMessage2 0x8def
#define ROM_ADDR_WriteBufferToScreen 0x8e92
#define ROM_ADDR_AwardGameTimerPoints 0xd312
#define ROM_ADDR_BackSceneryMetatiles 0x938a
#define ROM_ADDR_BlockBufferAdderData 0xe3ad
#define ROM_ADDR_BlockBufferChk_Enemy 0xe388
#define ROM_ADDR_BlockBufferChk_FBall 0xe39c
#define ROM_ADDR_BlockBufferCollision 0xe3f0
#define ROM_ADDR_BouncingBlockHandler 0xbeb3
#define ROM_ADDR_BrickQBlockMetatiles 0xbde8
#define ROM_ADDR_BrickShatterFreqData 0xf62b
#define ROM_ADDR_BulletBillCheepCheep 0xc69c
#define ROM_ADDR_CheckForBulletBillCV 0xe8be
#define ROM_ADDR_CheckForPUpCollision 0xd881
#define ROM_ADDR_CheckForVerticalFlip 0xea64
#define ROM_ADDR_CheckRightScreenBBox 0xe2de
#define ROM_ADDR_CheckToMirrorJSpring 0xeb4e
#define ROM_ADDR_CheckUpsideDownShell 0xe990
#define ROM_ADDR_ChkForLandJumpSpring 0xdec4
#define ROM_ADDR_ChkForPlayerC_LargeP 0xdb5f
#define ROM_ADDR_ChkLrgObjFixedLength 0x9baf
#define ROM_ADDR_ClearBuffersDrawIcon 0x8732
#define ROM_ADDR_ContinueBrickShatter 0xf640
#define ROM_ADDR_DefaultBlockObjTiles 0xebcd
#define ROM_ADDR_DemotedKoopaXSpdData 0xd851
#define ROM_ADDR_DestroyBlockMetatile 0x8a6b
#define ROM_ADDR_EnemyAnimTimingBMask 0xe876
#define ROM_ADDR_EnemyGfxTableOffsets 0xe840
#define ROM_ADDR_FindEventMusicHeader 0xf6f1
#define ROM_ADDR_GetAlternatePalette1 0x8643
#define ROM_ADDR_GetCurrentAnimOffset 0xf062
#define ROM_ADDR_GetMiscOffscreenBits 0xf19b
#define ROM_ADDR_GroundLevelLeadInHdr 0xf99a
#define ROM_ADDR_GroundLevelPart2AHdr 0xf97c
#define ROM_ADDR_GroundLevelPart2BHdr 0xf982
#define ROM_ADDR_GroundLevelPart2CHdr 0xf988
#define ROM_ADDR_GroundLevelPart3AHdr 0xf98e
#define ROM_ADDR_GroundLevelPart3BHdr 0xf994
#define ROM_ADDR_GroundLevelPart4AHdr 0xf9a0
#define ROM_ADDR_GroundLevelPart4BHdr 0xf9a6
#define ROM_ADDR_GroundLevelPart4CHdr 0xf9ac
#define ROM_ADDR_HBroWalkingTimerData 0xc326
#define ROM_ADDR_HandleAreaMusicLoopB 0xf6d4
#define ROM_ADDR_HandleEToBGCollision 0xdffa
#define ROM_ADDR_InitFlyingCheepCheep 0xc4a8
#define ROM_ADDR_InitializeNameTables 0x8e19
#define ROM_ADDR_Jumpspring_Y_PosData 0xb8b6
#define ROM_ADDR_MetatileGraphics_Low 0x8b08
#define ROM_ADDR_MoveESprColOffscreen 0xebc1
#define ROM_ADDR_MoveESprRowOffscreen 0xebb7
#define ROM_ADDR_MoveFlyingCheepCheep 0xcedf
#define ROM_ADDR_MovePlayerVertically 0xbf4d
#define ROM_ADDR_MoveSpritesOffscreen 0x8223
#define ROM_ADDR_MusicLengthLookupTbl 0xff66
#define ROM_ADDR_NightSnowPaletteData 0x8d3c
#define ROM_ADDR_NonMaskableInterrupt 0x8082
#define ROM_ADDR_OffscrJoypadBitsData 0xb036
#define ROM_ADDR_OffscreenBoundsCheck 0xd67a
#define ROM_ADDR_PlayerBGPriorityData 0x9125
#define ROM_ADDR_PlayerEnemyCollision 0xd853
#define ROM_ADDR_PlayerStarting_X_Pos 0x9116
#define ROM_ADDR_PlayerStarting_Y_Pos 0x911c
#define ROM_ADDR_PrintVictoryMessages 0x83f6
#define ROM_ADDR_PrintWarpZoneNumbers 0x8882
#define ROM_ADDR_QuestionBlockRow_Low 0x996b
#define ROM_ADDR_RelativeMiscPosition 0xf148
#define ROM_ADDR_RenderSceneryTerrain 0x9404
#define ROM_ADDR_ReplaceBlockMetatile 0x8a61
#define ROM_ADDR_RiseFallPiranhaPlant 0xd3ea
#define ROM_ADDR_SecondBoxVerticalChk 0xe34c
#define ROM_ADDR_SkipSoundSubroutines 0xf35d
#define ROM_ADDR_SpinCounterClockwise 0xd424
#define ROM_ADDR_VariableObjOfsRelPos 0xf165
#define ROM_ADDR_WaterEventMusEnvData 0xffa2
#define ROM_ADDR_AreaParserTaskControl 0x86e6
#define ROM_ADDR_AreaParserTaskHandler 0x92b0
#define ROM_ADDR_BlockBufferColli_Feet 0xe3e8
#define ROM_ADDR_BlockBufferColli_Head 0xe3e9
#define ROM_ADDR_BlockBufferColli_Side 0xe3ec
#define ROM_ADDR_ChangeSizeOffsetAdder 0xf09c
#define ROM_ADDR_CheckRightSideUpShell 0xe9a6
#define ROM_ADDR_ChkForBump_HammerBroJ 0xe124
#define ROM_ADDR_ChkSmallPlatCollision 0xd671
#define ROM_ADDR_DrawFirebar_Collision 0xcdbb
#define ROM_ADDR_EnemyToBGCollisionDet 0xdfc1
#define ROM_ADDR_FlagpoleScoreNumTiles 0xe541
#define ROM_ADDR_FloateyNumbersRoutine 0x84c3
#define ROM_ADDR_GetBlockOffscreenBits 0xf1b6
#define ROM_ADDR_GetEnemyOffscreenBits 0xf1af
#define ROM_ADDR_GetOffsetFromAnimCtrl 0xf0d0
#define ROM_ADDR_InitHorizFlySwimEnemy 0xc33d
#define ROM_ADDR_LakituAndSpinyHandler 0xc3a4
#define ROM_ADDR_LargePlatformBoundBox 0xe273
#define ROM_ADDR_MetatileGraphics_High 0x8b0c
#define ROM_ADDR_MoveBoundBoxOffscreen 0xe289
#define ROM_ADDR_MoveD_EnemyVertically 0xbf63
#define ROM_ADDR_MoveEnemyHorizontally 0xbf02
#define ROM_ADDR_MoveJ_EnemyVertically 0xbf92
#define ROM_ADDR_MushroomRetainerSaved 0x8d7c
#define ROM_ADDR_OperModeExecutionTree 0x8212
#define ROM_ADDR_PlayerHammerCollision 0xd7c4
#define ROM_ADDR_PositionPlayerOnHPlat 0xd614
#define ROM_ADDR_PositionPlayerOnVPlat 0xdc21
#define ROM_ADDR_PrintStatusBarNumbers 0x8f06
#define ROM_ADDR_QuestionBlockRow_High 0x9968
#define ROM_ADDR_RaiseFlagSetoffFWorks 0xd34e
#define ROM_ADDR_RelativeBlockPosition 0xf159
#define ROM_ADDR_RelativeEnemyPosition 0xf152
#define ROM_ADDR_RenderAttributeTables 0x896a
#define ROM_ADDR_ScrollLockObject_Warp 0x96f2
#define ROM_ADDR_SmallPlatformBoundBox 0xe24c
#define ROM_ADDR_SwimStompEnvelopeData 0xf3b1
#define ROM_ADDR_WSelectBufferTemplate 0x823f
#define ROM_ADDR_WriteBottomStatusLine 0x865a
#define ROM_ADDR_AlternateLengthHandler 0xf8c5
#define ROM_ADDR_ChkJumpspringMetatiles 0xdedd
#define ROM_ADDR_DrawExplosion_Fireball 0xed09
#define ROM_ADDR_DrawFloateyNumber_Coin 0xe655
#define ROM_ADDR_FireballEnemyCollision 0xd6d9
#define ROM_ADDR_GetBubbleOffscreenBits 0xf191
#define ROM_ADDR_GetEnemyBoundBoxOfsArg 0xdc54
#define ROM_ADDR_GetObjRelativePosition 0xf171
#define ROM_ADDR_GetPlayerOffscreenBits 0xf180
#define ROM_ADDR_HandlePowerUpCollision 0xd800
#define ROM_ADDR_IntermediatePlayerData 0xef9e
#define ROM_ADDR_JumpspringFrameOffsets 0xe878
#define ROM_ADDR_LargePlatformCollision 0xdb45
#define ROM_ADDR_MoveObjectHorizontally 0xbf0f
#define ROM_ADDR_MovePlayerHorizontally 0xbf09
#define ROM_ADDR_MoveSwimmingCheepCheep 0xcc4a
#define ROM_ADDR_PlatformSideCollisions 0xdbf5
#define ROM_ADDR_PositionPlayerOnS_Plat 0xdc19
#define ROM_ADDR_RelativeBubblePosition 0xf131
#define ROM_ADDR_RelativePlayerPosition 0xf12a
#define ROM_ADDR_ResidualMiscObjectCode 0xe392
#define ROM_ADDR_SmallPlatformCollision 0xdb7b
#define ROM_ADDR_SprObjectCollisionCore 0xe327
#define ROM_ADDR_UndergroundPaletteData 0x8cec
#define ROM_ADDR_VictoryModeSubroutines 0x83a0
#define ROM_ADDR_XMoveCntr_GreenPTroopa 0xcb45
#define ROM_ADDR_DrawExplosion_Fireworks 0xed17
#define ROM_ADDR_DrawPlayer_Intermediate 0xefa4
#define ROM_ADDR_EndOfCastleMusicEnvData 0xff96
#define ROM_ADDR_Entrance_GameTimerSetup 0x9131
#define ROM_ADDR_MoveAllSpritesOffscreen 0x8220
#define ROM_ADDR_MoveSixSpritesOffscreen 0xe5b3
#define ROM_ADDR_GetFireballOffscreenBits 0xf187
#define ROM_ADDR_LargePlatformSubroutines 0xc982
#define ROM_ADDR_LoadWaterEventMusEnvData 0xf909
#define ROM_ADDR_RelativeFireballPosition 0xf13b
#define ROM_ADDR_ResetSpritesAndScreenTimer 0x889d
#define VRAM_AddrTable_Low 0x805a
#define VRAM_AddrTable_High 0x806d
#define VRAM_Buffer_Offset 0x8080
#define WSelectBufferTemplate 0x823f
#define MushroomIconData 0x831d
#define DemoActionData 0x8340
#define DemoTimingData 0x8355
#define FloateyNumTileData 0x849f
#define ScoreUpdateData 0x84b7
#define AreaPalette 0x85bb
#define BGColorCtrl_Addr 0x85cb
#define BackgroundColors 0x85cf
#define PlayerColors 0x85d7
#define GameText 0x8752
#define TopStatusBarLine 0x8752
#define WorldLivesDisplay 0x8779
#define TwoPlayerTimeUp 0x8798
#define OnePlayerTimeUp 0x87a0
#define TwoPlayerGameOver 0x87ab
#define OnePlayerGameOver 0x87b3
#define WarpZoneWelcome 0x87c0
#define LuigiName 0x87ed
#define WarpZoneNumbers 0x87f2
#define GameTextOffsets 0x87fe
#define ColorRotatePalette 0x89c3
#define BlankPalette 0x89c9
#define Palette3Data 0x89d1
#define BlockGfxData 0x8a39
#define MetatileGraphics_Low 0x8b08
#define MetatileGraphics_High 0x8b0c
#define Palette0_MTiles 0x8b10
#define Palette1_MTiles 0x8bac
#define Palette2_MTiles 0x8c64
#define Palette3_MTiles 0x8c8c
#define WaterPaletteData 0x8ca4
#define GroundPaletteData 0x8cc8
#define UndergroundPaletteData 0x8cec
#define CastlePaletteData 0x8d10
#define DaySnowPaletteData 0x8d34
#define NightSnowPaletteData 0x8d3c
#define MushroomPaletteData 0x8d44
#define BowserPaletteData 0x8d4c
#define MarioThanksMessage 0x8d54
#define LuigiThanksMessage 0x8d68
#define MushroomRetainerSaved 0x8d7c
#define PrincessSaved1 0x8da8
#define PrincessSaved2 0x8dbf
#define WorldSelectMessage1 0x8dde
#define WorldSelectMessage2 0x8def
#define StatusBarData 0x8ef4
#define StatusBarOffset 0x8f00
#define DefaultSprOffsets 0x8fbc
#define Sprite0Data 0x8fcb
#define MusicSelectData 0x90e7
#define PlayerStarting_X_Pos 0x9116
#define AltYPosOffset 0x911a
#define PlayerStarting_Y_Pos 0x911c
#define PlayerBGPriorityData 0x9125
#define GameTimerData 0x912d
#define HalfwayPageNybbles 0x91bd
#define BSceneDataOffsets 0x92f7
#define BackSceneryData 0x92fa
#define BackSceneryMetatiles 0x938a
#define FSceneDataOffsets 0x93ae
#define ForeSceneryData 0x93b1
#define TerrainMetatiles 0x93d8
#define TerrainRenderBits 0x93dc
#define BlockBuffLowBounds 0x9504
#define FrenzyIDData 0x9728
#define PulleyRopeMetatiles 0x97b7
#define CastleMetatiles 0x97cf
#define SidePipeShaftData 0x989f
#define SidePipeTopPart 0x98a3
#define SidePipeBottomPart 0x98a7
#define VerticalPipeData 0x98dd
#define CoinMetatileData 0x99ee
#define C_ObjectRow 0x99fb
#define C_ObjectMetatile 0x99fe
#define SolidBlockMetatiles 0x9a25
#define BrickMetatiles 0x9a29
#define StaircaseHeightData 0x9aa5
#define StaircaseRowData 0x9aae
#define HoleMetatiles 0x9b3d
#define BlockBufferAddr 0x9bdd
#define AreaDataOfsLoopback 0x9bf8
#define WorldAddrOffsets 0x9cb4
#define AreaAddrOffsets 0x9cbc
#define World1Areas 0x9cbc
#define World2Areas 0x9cc1
#define World3Areas 0x9cc6
#define World4Areas 0x9cca
#define World5Areas 0x9ccf
#define World6Areas 0x9cd3
#define World7Areas 0x9cd7
#define World8Areas 0x9cdc
#define EnemyAddrHOffsets 0x9ce0
#define EnemyDataAddrLow 0x9ce4
#define EnemyDataAddrHigh 0x9d06
#define AreaDataHOffsets 0x9d28
#define AreaDataAddrLow 0x9d2c
#define AreaDataAddrHigh 0x9d4e
#define E_CastleArea1 0x9d70
#define E_CastleArea2 0x9d97
#define E_CastleArea3 0x9db0
#define E_CastleArea4 0x9ddf
#define E_CastleArea5 0x9e0a
#define E_CastleArea6 0x9e1f
#define E_GroundArea1 0x9e59
#define E_GroundArea2 0x9e7e
#define E_GroundArea3 0x9e9b
#define E_GroundArea4 0x9ea9
#define E_GroundArea5 0x9ed0
#define E_GroundArea6 0x9f01
#define E_GroundArea7 0x9f1f
#define E_GroundArea8 0x9f3c
#define E_GroundArea9 0x9f51
#define E_GroundArea10 0x9f7b
#define E_GroundArea11 0x9f7c
#define E_GroundArea12 0x9fa0
#define E_GroundArea13 0x9fa9
#define E_GroundArea14 0x9fce
#define E_GroundArea15 0x9ff1
#define E_GroundArea16 0x9ffa
#define E_GroundArea17 0x9ffb
#define E_GroundArea18 0xa035
#define E_GroundArea19 0xa060
#define E_GroundArea20 0xa08e
#define E_GroundArea21 0xa0aa
#define E_GroundArea22 0xa0b3
#define E_UndergroundArea1 0xa0d8
#define E_UndergroundArea2 0xa105
#define E_UndergroundArea3 0xa133
#define E_WaterArea1 0xa160
#define E_WaterArea2 0xa171
#define E_WaterArea3 0xa19b
#define L_CastleArea1 0xa1af
#define L_CastleArea2 0xa210
#define L_CastleArea3 0xa28f
#define L_CastleArea4 0xa302
#define L_CastleArea5 0xa36f
#define L_CastleArea6 0xa3fa
#define L_GroundArea1 0xa46b
#define L_GroundArea2 0xa4ce
#define L_GroundArea3 0xa537
#define L_GroundArea4 0xa58a
#define L_GroundArea5 0xa619
#define L_GroundArea6 0xa68e
#define L_GroundArea7 0xa6f3
#define L_GroundArea8 0xa748
#define L_GroundArea9 0xa7cd
#define L_GroundArea10 0xa832
#define L_GroundArea11 0xa83b
#define L_GroundArea12 0xa87a
#define L_GroundArea13 0xa88f
#define L_GroundArea14 0xa8f6
#define L_GroundArea15 0xa95b
#define L_GroundArea16 0xa9ce
#define L_GroundArea17 0xa9ff
#define L_GroundArea18 0xaa92
#define L_GroundArea19 0xab05
#define L_GroundArea20 0xab7e
#define L_GroundArea21 0xabd7
#define L_GroundArea22 0xac02
#define L_UndergroundArea1 0xac35
#define L_UndergroundArea2 0xacd8
#define L_UndergroundArea3 0xad79
#define L_WaterArea1 0xae06
#define L_WaterArea2 0xae45
#define L_WaterArea3 0xaec0
#define X_SubtracterData 0xb034
#define OffscrJoypadBitsData 0xb036
#define Hidden1UpCoinAmts 0xb2c2
#define ClimbAdderLow 0xb3c7
#define ClimbAdderHigh 0xb3cb
#define JumpMForceData 0xb424
#define FallMForceData 0xb42b
#define PlayerYSpdData 0xb432
#define InitMForceData 0xb439
#define MaxLeftXSpdData 0xb440
#define MaxRightXSpdData 0xb443
#define FrictionData 0xb447
#define Climb_Y_SpeedData 0xb44a
#define Climb_Y_MForceData 0xb44d
#define PlayerAnimTmrData 0xb58c
#define FireballXSpdData 0xb687
#define Bubble_MForceData 0xb74b
#define BubbleTimerData 0xb74d
#define FlagpoleScoreMods 0xb84b
#define FlagpoleScoreDigits 0xb850
#define Jumpspring_Y_PosData 0xb8b6
#define VineHeightData 0xb949
#define CannonBitmasks 0xb9ba
#define BulletBillXSpdData 0xba31
#define HammerEnemyOfsData 0xba89
#define HammerXSpdData 0xba92
#define CoinTallyOffsets 0xbbf8
#define ScoreOffsets 0xbbfa
#define StatusBarNybbles 0xbbfc
#define BlockYPosAdderData 0xbceb
#define BrickQBlockMetatiles 0xbde8
#define MaxSpdBlockData 0xbf9f
#define LoopCmdWorldNumber 0xc06b
#define LoopCmdPageNumber 0xc076
#define LoopCmdYPosition 0xc081
#define NormalXSpdData 0xc30c
#define HBroWalkingTimerData 0xc326
#define PRDiffAdjustData 0xc398
#define FirebarSpinSpdData 0xc44f
#define FirebarSpinDirData 0xc454
#define FlyCCXPositionData 0xc488
#define FlyCCXSpeedData 0xc498
#define FlyCCTimerData 0xc4a4
#define FlameYPosData 0xc59d
#define FlameYMFAdderData 0xc5a1
#define FireworksXPosData 0xc631
#define FireworksYPosData 0xc637
#define Bitmasks 0xc68a
#define Enemy17YPosData 0xc692
#define SwimCC_IDData 0xc69a
#define PlatPosDataLow 0xc86b
#define PlatPosDataHigh 0xc86e
#define HammerThrowTmrData 0xc9ce
#define XSpeedAdderData 0xc9d0
#define RevivedXSpeed 0xc9d4
#define HammerBroJumpLData 0xca10
#define BlooberBitmasks 0xcb87
#define SwimCCXMoveData 0xcc46
#define FirebarPosLookupTbl 0xccc7
#define FirebarMirrorData 0xcd2a
#define FirebarTblOffsets 0xcd2e
#define FirebarYPos 0xcd3a
#define PRandomSubtracter 0xced5
#define FlyCCBPriority 0xceda
#define LakituDiffAdj 0xcf25
#define BridgeCollapseData 0xcfdd
#define PRandomRange 0xd061
#define FlameTimerData 0xd1d1
#define StarFlagYPosAdder 0xd2cd
#define StarFlagXPosAdder 0xd2d1
#define StarFlagTileData 0xd2d5
#define BowserIdentities 0xd736
#define ResidualXSpdData 0xd84d
#define KickedShellXSpdData 0xd84f
#define DemotedKoopaXSpdData 0xd851
#define KickedShellPtsData 0xd892
#define StompedEnemyPtsData 0xd965
#define RevivalRateData 0xd9d2
#define SetBitsMask 0xda25
#define ClearBitsMask 0xda2c
#define PlayerPosSPlatData 0xdc17
#define PlayerBGUpperExtent 0xdc62
#define AreaChangeTimerData 0xde03
#define ClimbXPosAdder 0xde25
#define ClimbPLocAdder 0xde27
#define FlagpoleYPosData 0xde29
#define SolidMTileUpperExt 0xdf8b
#define ClimbMTileUpperExt 0xdf96
#define EnemyBGCStateData 0xdfb9
#define EnemyBGCXSpdData 0xdfbf
#define BoundBoxCtrlData 0xe1fd
#define BlockBufferAdderData 0xe3ad
#define BlockBuffer_X_Adder 0xe3b0
#define BlockBuffer_Y_Adder 0xe3cc
#define VineYPosAdder 0xe433
#define FirstSprXPos 0xe4c0
#define FirstSprYPos 0xe4c4
#define SecondSprXPos 0xe4c8
#define SecondSprYPos 0xe4cc
#define FirstSprTilenum 0xe4d0
#define SecondSprTilenum 0xe4d4
#define HammerSprAttrib 0xe4d8
#define FlagpoleScoreNumTiles 0xe541
#define JumpingCoinTiles 0xe682
#define PowerUpGfxTable 0xe6be
#define PowerUpAttributes 0xe6ce
#define EnemyGraphicsTable 0xe73e
#define EnemyGfxTableOffsets 0xe840
#define EnemyAttributeData 0xe85b
#define EnemyAnimTimingBMask 0xe876
#define JumpspringFrameOffsets 0xe878
#define DefaultBlockObjTiles 0xebcd
#define ExplosionTiles 0xed06
#define PlayerGfxTblOffsets 0xee07
#define PlayerGraphicsTable 0xee17
#define SwimKickTileNum 0xeee7
#define IntermediatePlayerData 0xef9e
#define ChangeSizeOffsetAdder 0xf09c
#define ObjOffsetData 0xf1a5
#define XOffscreenBitsData 0xf1e3
#define DefaultXOnscreenOfs 0xf1f3
#define YOffscreenBitsData 0xf22b
#define DefaultYOnscreenOfs 0xf234
#define HighPosUnitData 0xf237
#define SwimStompEnvelopeData 0xf3b1
#define ExtraLifeFreqData 0xf4d4
#define PowerUpGrabFreqData 0xf4da
#define PUp_VGrow_FreqData 0xf4f8
#define BrickShatterFreqData 0xf62b
#define MusicHeaderData 0xf90d
#define TimeRunningOutHdr 0xf93e
#define Star_CloudHdr 0xf943
#define EndOfLevelMusHdr 0xf949
#define ResidualHeaderData 0xf94e
#define UndergroundMusHdr 0xf953
#define SilenceHdr 0xf958
#define CastleMusHdr 0xf95c
#define VictoryMusHdr 0xf961
#define GameOverMusHdr 0xf966
#define WaterMusHdr 0xf96b
#define WinCastleMusHdr 0xf971
#define GroundLevelPart1Hdr 0xf976
#define GroundLevelPart2AHdr 0xf97c
#define GroundLevelPart2BHdr 0xf982
#define GroundLevelPart2CHdr 0xf988
#define GroundLevelPart3AHdr 0xf98e
#define GroundLevelPart3BHdr 0xf994
#define GroundLevelLeadInHdr 0xf99a
#define GroundLevelPart4AHdr 0xf9a0
#define GroundLevelPart4BHdr 0xf9a6
#define GroundLevelPart4CHdr 0xf9ac
#define DeathMusHdr 0xf9b2
#define Star_CloudMData 0xf9b8
#define GroundM_P1Data 0xfa01
#define SilenceData 0xfa1c
#define GroundM_P2AData 0xfa49
#define GroundM_P2BData 0xfa75
#define GroundM_P2CData 0xfa9d
#define GroundM_P3AData 0xfac2
#define GroundM_P3BData 0xfadb
#define GroundMLdInData 0xfaf9
#define GroundM_P4AData 0xfb25
#define GroundM_P4BData 0xfb4b
#define DeathMusData 0xfb72
#define GroundM_P4CData 0xfb74
#define CastleMusData 0xfba4
#define GameOverMusData 0xfc45
#define TimeRunOutMusData 0xfc72
#define WinLevelMusData 0xfcb0
#define UndergroundMusData 0xfd11
#define WaterMusData 0xfd52
#define EndOfCastleMusData 0xfe51
#define VictoryMusData 0xfec8
#define FreqRegLookupTbl 0xff00
#define MusicLengthLookupTbl 0xff66
#define EndOfCastleMusicEnvData 0xff96
#define AreaMusicEnvData 0xff9a
#define WaterEventMusEnvData 0xffa2
#define BowserFlameEnvData 0xffca
#define BrickShatterEnvData 0xffea

#endif
