name: Build and Deploy WASM

on:
  push:
    branches:
      - '**'  # Matches all branches
  pull_request:
    branches:
      - main  # Also run on PRs targeting main
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LLVM and Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm clang lld

      - name: Build WASM
        run: make wasm

      - name: Prepare deployment
        run: |
          mkdir -p dist
          cp -r web/* dist/
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true  # Automatically remove deleted files from the deploy branch
          token: ${{ secrets.GITHUB_TOKEN }}
